### ISSUE TITLE
Crash alongside Boleatte on Quilted Fabric API

### ISSUE THREAD

**Issue by DakotaPride** [KyaniteMods/DeeperAndDarker#100]
**Description**:
Unexpected crash upon startup while mod 'Boleatte' is loaded alongside 'Deeper And Darker' while running on 'Quilted Fabric API'

**To Reproduce**:
Steps to reproduce the behaviour:
1. Install Boleatte (v0.2.1) with Deeper And Darker (1.1.4) (alongside GeckoLib and Quilted Fabric API, of course)
2. Load Minecraft Game On Quilt Loader of some kind (Prism Launcher used, though should happen with any launcher)

**Screenshots**:
If applicable, add screenshots to help explain your problem. (None available)

**Additional context**:
[Crash Report Provided](https://pastebin.com/4aU7tvz3)
[Issue Report On Boleatte](https://github.com/DakotaPride/Boleatte/issues/3)

**Comment by NewJumper** [comment]
Seems to be similar to #98. However, that issue seems to have been fixed. Definitely looking further into this issue.

**Comment by DakotaPride** [comment]
It doesn't seem to be fixed. I think it's a per-mod thing while using 'custom portal api', which I use in my mod as well. I see that it was fixed with 'Paradise Lost'. If this was fixed via something in the code of 'Deeper And Darker', then replicating it in a similar manner should fix it. If it was done via altering the code of Paradise Lost, then I may be able to replicate that into my code and see that fixes it as well. Let me know if there is anything I can do on my end to fix the issue, or if I just have to wait until a fix is released.

[Issue Report [comment]](https://github.com/DakotaPride/Boleatte/issues/3#issuecomment-1310612913)

**Comment by ang-xd** [comment]
Boleatte needs to update Custom Portal API.
