### ISSUE TITLE
Sculk Shrieker On Water?

### ISSUE THREAD

**Issue by Khairul2011** [KyaniteMods/DeeperAndDarker#103]
**Description**:
Hey That's Is Say For What The Heck Is This?

**To Reproduce**:

Go to Ancient Temple

Tp 16 ~ -1776

Up To Soul Elytra

Sculk Shrieker On Water For Ancient Temple?

**Screenshots**:
![2022-11-19_20 37 24](https://user-images.githubusercontent.com/118614927/202853822-c7367bbd-de50-463b-bd40-bae57ea576bd.png)

**Additional context**:

Please Of Without Water On Fabric Good Luck

**Comment by NewJumper** [comment]
provide a more clear explanation of the issue and what should be fixed
