### ISSUE TITLE
Adding compability with Trinkets API

### ISSUE THREAD

**Issue by ShadedPL** [KyaniteMods/DeeperAndDarker#106]
**Description**:
Trinkets allows us to put the Elytra in the cape slot, would be awesome if the Soul Elytra could do the same, especially as it is a late game item
![image](https://user-images.githubusercontent.com/4216212/203832306-07e8eac4-8c84-467d-8929-c164cc00f46e.png)

Link to Trinkets mod:
https://www.curseforge.com/minecraft/mc-mods/trinkets

**Comment by nitrodynamite18** [comment]
The Elytra slot mod added compatibility for Deeper and Darker, meaning you just have to add it and the Soul Elytra will work in Trinkets slots.
https://www.curseforge.com/minecraft/mc-mods/elytra-slot
