### ISSUE TITLE
Sculk Snapper - Ticking Entity NPE crash

### ISSUE THREAD

**Issue by Jeuvke** [KyaniteMods/DeeperAndDarker#107]
While walking around the otherside I neared a structure, when the server suddenly crashed with an NPE. The crash kept on happening every time I logged back in.

`java.lang.NullPointerException: Cannot invoke "net.minecraft.world.entity.LivingEntity.m_20154_()" because the return value of "com.kyanite.deeperdarker.registry.entities.custom.SculkSnapperEntity.m_5448_()" is null`

https://mclo.gs/M5OjQMB

**Comment by Seegras** [comment]
There's something deeply wrong with them anyway: Setting the game to peaceful inhibits them from spawning, but already existing ones remain.

Also, they somehow teleport to you if you're on a block above them, even if they're 60 blocks below you. 

And I'm not sure through what blocks they "dig" through; but I'm pretty sure a lot of them they shouldn't. Like glass.
