### ISSUE TITLE
Sculk Transmitter not opening containers more than 8 blocks away

### ISSUE THREAD

**Issue by marianyp** [KyaniteMods/DeeperAndDarker#108]
**Description**:
When using the sculk transmitter, if you're more than 8 blocks away then the container GUI opens then closes immediately.

**To Reproduce**:
1. Use Forge **43.1.52** and Deeper and Darker version **1.1.3**
2. Link a Sculk Transmitter to a chest/container
3. Move more than 8 blocks away and try to use the Sculk Transmitter

**Additional context**:
I'm not sure if the root issue is with vanilla Minecraft or forge. I loaded up an empty forge instance (without deeper and darker), and set the reach attribute of the player to something high like 10 blocks. I then tried opening a chest/container. The same issue happened where the container GUI appeared for a split second and then closed. It's as if there's some built-in limit on how far the player can be when opening containers.

**Comment by NewJumper** [comment]
by chest/container, are you including furnaces, smokers, and stonecutters?
or is the issue only for chests?

**Comment by marianyp** [comment]
> by chest/container, are you including furnaces, smokers, and stonecutters? or is the issue only for chests?

All container GUIs it seems. Same issue happening with furnaces.

**Comment by NewJumper** [comment]
I was not able to recreate such issues, so it must have been fixed in dev.

**Comment by nitrodynamite18** [comment]
Sculk Transmitter functionality change means this bug is no longer relevant.
