### ISSUE TITLE
sinicization

### ISSUE THREAD

**Issue by 54dsa** [KyaniteMods/DeeperAndDarker#109]
Sinicization of 0.1.6
[zh_cn.zip](https://github.com/KyaniteMods/DeeperAndDarker/files/10097612/zh_cn.zip)

**Comment by nitrodynamite18** [comment]
Please submit all translation suggestions to the Crowdin page for the project. Our proofreaders will approve suggestions and approved additions will be automatically fetched from Crowdin.
