### ISSUE TITLE
[1.19.2] Incompatible with latest Geode+ Update

### ISSUE THREAD

**Issue by aking4125** [KyaniteMods/DeeperAndDarker#113]
**Mod Version**: 1.1.3

**Mod Loader**: forge 43.1.57+

**Description**:
Hello, upon adding both the latest version of Deeper Darker and Geode+, the game crashes with the following report citing Deeper Darker as the issue: [crash-2022-12-09_10.07.31-fml.txt](https://github.com/KyaniteMods/DeeperAndDarker/files/10195898/crash-2022-12-09_10.07.31-fml.txt)

Removing either mod fixes this problem. Any ideas?

**Additional context**:
This issue was mentioned in the Geode+ Github by another user: #https://github.com/YeoXuHang/Geode-Plus/issues/23

**Comment by Mathio95** [comment]
Same Issue

**Comment by cecaelion** [comment]
This also happens with Quilt/Fabric: 
[crash-2022-12-10_13.28.24-client.txt](https://github.com/KyaniteMods/DeeperAndDarker/files/10200889/crash-2022-12-10_13.28.24-client.txt)

**Comment by vizthex123** [comment]
Hope this gets fixed soon. Tried downgrading both a few times, and it seems nothing fixes it.

**Comment by aking4125** [comment]
Either the latest version of Deeper Darker fixed it or Geode+. At least on the forged end.

Version Deeper Darker [Forge] 1.1.5 and Geode+ [Forge] 1.1.2 together seemed to fix the issue on my end.

**Comment by Willem07** [comment]
This also happens with illuminations mod

**Comment by ang-xd** [comment]
Should be fixed in latest version of Deeper and Darker (1.1.6). Waiting on Geode+ to update.
