### ISSUE TITLE
Echo signs cannot be used, are invisible and have no texture.

### ISSUE THREAD

**Issue by KaboomRoads** [KyaniteMods/DeeperAndDarker#116]
**Mod Version**: v1.1.6 for 1.19.2

**Mod Loader**: forge

**Description**:
When I place an Echo Sign it shows the edit menu for a split second with no texture then kicks me out, the sign is now there but invisible.

**To Reproduce**:
1. Place an Echo Sign.

There are no new errors in the console.

**Additional context**:
Using latest deeperdarker forge version.
Using latest 1.19.2 forge geckolib version.
Using latest 1.19.2 forge version. (43.2.0)

**Comment by NewJumper** [comment]
fixed in upcoming update
