### ISSUE TITLE
Sculk attacks itself.

### ISSUE THREAD

**Issue by KaboomRoads** [KyaniteMods/DeeperAndDarker#117]
**Mod Version**: v1.1.6 for 1.19.2

**Mod Loader**: forge

**Description**:
Custom Sculk mobs activate Sculk Sensors and The Warden.
The Sculk Jaw hurts custom Sculk mobs and The Warden.
The Warden can target custom Sculk mobs.

**Comment by NewJumper** [comment]
fixed in upcoming update
