### ISSUE TITLE
v1.1.6/Fabric - Naturally generated shrieker in ancient temple won't get activated by a sensor

### ISSUE THREAD

**Issue by LinuxSquare** [KyaniteMods/DeeperAndDarker#118]
**Mod Version**: 1.1.6

**Mod Loader**: fabric

**Description**:
Normally, if someone walks pass a sensor and a shrieker is near to it, the sensor sends the signal to the shrieker to alert the Warden.
However this doesn't occur with the naturally generated sculk shriekers in the ancient temple. 
Since I couldn't find a config-option to enable this, I'm very certain, that it's a bug of the mod.

I don't know, if it's intended to make it a little easier. 
If so, it would be nice, to have it as a config option, so we have the ability to enable or disable the shrieker, when called by a sensor.

**To Reproduce**:
1. Generate a new world
2. find an ancient city and enter the Otherside
3. find an ancient temple
4. walk around near the shriekers (if no sensors are available, place them manually)

**Screenshots**:
No screenshots, but a kinda long video:
https://youtu.be/DhPXGiPZH0g

I made some timestamps, so it's easier to navigate through the video.

**Additional context**:
What I've noticed next to the main problem is, that the Warden can't spawn, when the floor is submerged in water.
Instead it growls angrily and doesn't spawn (also seen in the video). 

However, if I surround the waterlogged shrieker with solid blocks, the Warden can spawn without any problems.

**Comment by nitrodynamite18** [comment]
Is gamerule doWardenSpawning set to true?
