### ISSUE TITLE
Deeper and Darker overrides Quark ancient sapling loot spawns

### ISSUE THREAD

**Issue by Wgairborne** [KyaniteMods/DeeperAndDarker#130]
**Mod Version**: 1.1.6

**Mod Loader**: forge

**Description**:
Deeper and Darker's method of modifying the ancient city loot tables ends up excluding Quark's new ancient sapling spawns from them.

I made sure it was Deeper and Darker's fault by loading up an instance with just Quark installed, and it worked fine.

**To Reproduce**:
1. Install Deeper and Darker and Quark on their latest versions.
2. Load up a new world and teleport to an ancient city.
3. Loot all the chests and notice that there isn't a single sapling to be seen.

**Screenshots**:
N/A

**Additional context**:
N/A

**Comment by FearAK** [comment]
Is this still not fixed? I can't find any ancient saplings in my world with quark and deeper and darker

**Comment by Wgairborne** [comment]
seems the issue has been completely ignored... shame

**Comment by NewJumper** [comment]
fixed in upcoming update
