### ISSUE TITLE
Sculk Stone and Gloomslate have no sounds

### ISSUE THREAD

**Issue by BreadieSB** [KyaniteMods/DeeperAndDarker#131]
**Mod Version**: 1.1.6

**Mod Loader**: Fabric 1.19.2

**Description**:
Sculk Stone, Gloomslate and related blocks make no sound when mined, walked on, ect.

**To Reproduce**:
1. Mine or walk on Sculk Stone or Gloomslate

**Comment by NottDAG-Gsimus** [comment]
It actually occurs with ancient pots aswell

**Comment by Pedro270707** [comment]
Fixed in 1.2.0
