### ISSUE TITLE
When i light the portal it doesnt let me through 

### ISSUE THREAD

**Issue by P0tato2** [KyaniteMods/DeeperAndDarker#133]
Mod Version 1.19.2

Mod Loader: forge

Description
When i step in the portal nothing happens and it doesn't tp me to the otherside dimension

1. Find ancient city
2. Light portal
3. step in it 
4. nothing happens

Screenshot

![2023-01-21_23 24 09](https://user-images.githubusercontent.com/123284737/213900543-fbf978cd-efeb-48ce-8028-6764925300b7.png)

**Comment by HockeyZman2000** [comment]
Is there a solution to this problem? I'm encountering the same thing
