### ISSUE TITLE
Parsing errors loading recipe mekanism

### ISSUE THREAD

**Issue by Ulisesrec** [KyaniteMods/DeeperAndDarker#134]
**Mod Version**: 1.1.6

**Mod Loader**: forge

**Description**:
I get a lot of parsing errors trying to load recipe mekanism in a forge server, the server does initiate but it gives a lot of those errors

**To Reproduce**:
1. Install mod on forge server
2. run the server
3. See error

**Additional context**:
Log: https://drive.google.com/file/d/15rH7yQLdj2CRS_9ALTMJK-7bsfUtDB6Q/view?usp=share_link

**Comment by nitrodynamite18** [comment]
Already fixed, will be released in the next update for the mod.
