### ISSUE TITLE
Several Errors upon startup

### ISSUE THREAD

**Issue by TheAyes** [KyaniteMods/DeeperAndDarker#135]
**Mod Version**: 1.1.14

**Mod Loader**: quilt

**Description**:
`Json Syntax Error: Duplicate key block.sculk_jaw.break`
`Non [a-z0-9/._-] character in path of location: deeperdarker:animations/VoxelShape.java`
`[STDERR]: java.lang.IndexOutOfBoundsException: Index -1 out of bounds for length 0`

https://mclo.gs/5m6H5vZ

**Comment by nitrodynamite18** [comment]
First issue fixed by pull request #120.
