### ISSUE TITLE
Sculk Transmitter doesn't work further than seven blocks away from the chest

### ISSUE THREAD

**Issue by HaelStegaria** [KyaniteMods/DeeperAndDarker#136]
**Mod Version**: 1.1.6

**Mod Loader**: forge

**Description**:
When a Sculk Transmitter is bound to a chest, right clicking the sculk transmitter within a six block radius will open the chest, like it's supposed to. But at eight blocks away or more, when you right click the transmitter the chest screen will flash open for a fraction of a second and disappear before you can do anything. And, side note, the transmitter doesn't link to Quark variant chests.

**To Reproduce**:
1. Open a new world with the mod installed
2. Place a chest and link a transmitter.
3. Right click the transmitter close to the chest--it'll open
4. Walk eight blocks away and right click the transmitter--it only flashes open briefly

**Screenshots**:

**Additional context**:
Add any other context about the problem here: crash reports, logs, and any other details.

**Comment by nitrodynamite18** [comment]
Same as #108, this issue is irrelevant due to the Sculk Transmitter's new functionality for the next update.
