### ISSUE TITLE
Game Crashes with Fabric Loader

### ISSUE THREAD

**Issue by Gamerash224** [KyaniteMods/DeeperAndDarker#139]
**Mod Version**: 1.1.4

**Mod Loader**: Fabric

**Description**:
Latest version can't launch with the latest fabric api. error says customportal.api is causing the error.

**To Reproduce**:
1. have deeper and darker, fabric api, and geckolib in mod folder
2. attempt to start the game from the minecraft launcher
3. Receive error message

**Screenshots**:

![Screenshot_20230219_030546](https://user-images.githubusercontent.com/125792120/219937771-eee9280c-cc6c-4dfd-a98c-04c73a0a850c.png)

![Screenshot_20230219_030559](https://user-images.githubusercontent.com/125792120/219937778-2e45a686-a2d8-4d9f-adc2-300a42bc7abe.png)

![Screenshot_20230219_032325](https://user-images.githubusercontent.com/125792120/219937783-20126841-9093-4d14-904c-0c37a70db1be.png)

I'm using the latest versions of everything, so I'm not sure what the problem is. I literally uninstalled and deleted my entire .minecraft file from %appdata%, reinstalled minecraft and fabric, and I only have the fabric api, geckolib, and deeper and darker mod in the mods folder.

**Comment by Gamerash224** [comment]
I should say I removed the sodium mod and tried it again, just in case that was the problem. Same result.

**Comment by nitrodynamite18** [comment]
Please upload the entire crash report file.
