### ISSUE TITLE
Skulk Transmitter

### ISSUE THREAD

**Issue by Pronana** [KyaniteMods/DeeperAndDarker#141]
**Mod Version**: 1.1.6

**Mod Loader**: fabric

**Description**:
Skulk Transmitter doesn't work between dimensions.

**To Reproduce**:
1. Link Skulk Transmitter to chest
2. Go to a different dimension
3. Skulk Transmitter unlinks

**Additional context**:
I tried loading the chunk using chunkloaders or alt accounts, it still happened.

**Comment by nitrodynamite18** [comment]
See issue #108.
