### ISSUE TITLE
Immersive portals compatibility toggle

### ISSUE THREAD

**Issue by 42Cyborg** [KyaniteMods/DeeperAndDarker#144]
I would absolutely love to see a config option to enable immersive portals support. I believe if you are able to turn off the event to trigger your default portal generation and allow immersive portals to handle the generation instead it might be possible.

but in any case I absolutely love the mod! keep up the great work!

**Comment by nitrodynamite18** [comment]
The problem with Immersive Portals compatibility is that the portals are not the same size.

**Comment by ang-xd** [comment]
Unfortunately not possible on our end.
