### ISSUE TITLE
Several blocks have no sounds and are silent

### ISSUE THREAD

**Issue by Puffadillo** [KyaniteMods/DeeperAndDarker#148]
**Mod Version**: 1.1.6

**Mod Loader**: Fabric

**Description**:
Certain blocks such as sculk stone, gloomslate, vases, and several more have no sounds assigned to them, resulting in some awkward silent gameplay. Here's a video example:

https://user-images.githubusercontent.com/108554062/226789238-c1504665-8a27-4f48-8f48-c77cbf840878.mp4

I am playing with [Presence Footsteps](https://www.curseforge.com/minecraft/mc-mods/presence-footsteps/) which makes footsteps louder (and the lack of sounds more noticeable) but I've also tested this in a fresh instance with only Fabric API, Deeper and Darker, and GeckoLib with the same bug.

**Comment by Pedro270707** [comment]
Fixed in 1.2.0
