### ISSUE TITLE
Can't go through portal

### ISSUE THREAD

**Issue by EpicM147** [KyaniteMods/DeeperAndDarker#151]
**Mod Version**: 1.1.6

**Mod Loader**: forge

**Description**:
When I lite the portal with the Heart of the deep the portal lites but when I step in it nothing happens

![image](https://user-images.githubusercontent.com/129674613/229360273-2e20cdaa-85c7-446c-8fba-6e670e94d225.png)

**Comment by DarthCaesium** [comment]
Same issue with me

**Comment by NewJumper** [comment]
fixed in upcoming 1.2.0 update

**Comment by EpicM147** [comment]
1.2.0 will it be on 1.20.1? Cannot wait to find more bugs.
