### ISSUE TITLE
crash every time I go through the portal

### ISSUE THREAD

**Issue by remiimber** [KyaniteMods/DeeperAndDarker#152]
**Mod Version**: 1.1.6

**Mod Loader**: fabric

**Description**:
every time I go through the portal my game crashes

**To Reproduce**:
1. open the portal '...'
2. enter the portal '...'
3. "loading world" (sometimes It loads and the crashes)'...'

**Screenshots**:

**Additional context**:
---- Minecraft Crash Report ----
// Who set us up the TNT?

Time: 2023-04-02 23:21:08
Description: Exception ticking world

java.lang.NoSuchMethodError: 'software.bernie.geckolib3.core.manager.AnimationFactory software.bernie.geckolib3.util.GeckoLibUtil.createFactory(software.bernie.geckolib3.core.IAnimatable)'
	at com.kyanite.deeperdarker.registry.entities.custom.SculkSnapperEntity.<init>(SculkSnapperEntity.java:61)
	at net.minecraft.class_1299.method_5883(class_1299.java:487)
	at net.minecraft.class_1948.method_24931(class_1948.java:355)
	at net.minecraft.class_1948.method_24930(class_1948.java:284)
	at net.minecraft.class_1948.method_8663(class_1948.java:212)
	at net.minecraft.class_1948.method_27821(class_1948.java:200)
	at net.minecraft.class_3215.method_14161(class_3215.java:376)
	at net.minecraft.class_3215.method_12127(class_3215.java:323)
	at net.minecraft.class_3218.method_18765(class_3218.java:319)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:875)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:819)
	at net.minecraft.class_1132.method_3748(class_1132.java:98)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:665)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at java.base/java.lang.Thread.run(Thread.java:833)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at com.kyanite.deeperdarker.registry.entities.custom.SculkSnapperEntity.<init>(SculkSnapperEntity.java:61)
	at net.minecraft.class_1299.method_5883(class_1299.java:487)
	at net.minecraft.class_1948.method_24931(class_1948.java:355)
	at net.minecraft.class_1948.method_24930(class_1948.java:284)
	at net.minecraft.class_1948.method_8663(class_1948.java:212)
	at net.minecraft.class_1948.method_27821(class_1948.java:200)
	at net.minecraft.class_3215.method_14161(class_3215.java:376)
	at net.minecraft.class_3215.method_12127(class_3215.java:323)
	at net.minecraft.class_3218.method_18765(class_3218.java:319)

-- Affected level --
Details:
	All players: 1 total; [class_3222['carrotysoup'/234, l='ServerLevel[New World]', x=-766.12, y=103.00, z=-307.73]]
	Chunk stats: 1053
	Level dimension: deeperdarker:otherside
	Derived: true
	Level spawn location: World: (0,63,0), Section: (at 0,15,0 in 0,3,0; chunk contains blocks 0,0,0 to 15,127,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,127,511)
	Level time: 18906 game time, 18906 day time
	Level name: New World
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
	Level weather: Rain time: 88123 (now: false), thunder time: 81194 (now: false)
	Known server brands: fabric
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:875)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:819)
	at net.minecraft.class_1132.method_3748(class_1132.java:98)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:665)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at java.base/java.lang.Thread.run(Thread.java:833)

-- System Details --
Details:
	Minecraft Version: 1.19.2
	Minecraft Version ID: 1.19.2
	Operating System: Mac OS X (aarch64) version 12.6
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 874163320 bytes (833 MiB) / 2147483648 bytes (2048 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 10
	Processor Vendor: Apple Inc.
	Processor Name: Apple M1 Pro
	Identifier: Apple Inc. Family 0x1b588bb3 Model 0 Stepping 0
	Microarchitecture: ARM64 SoC: Firestorm + Icestorm
	Frequency (GHz): 24.00
	Number of physical packages: 1
	Number of physical CPUs: 10
	Number of logical CPUs: 10
	Graphics card #0 name: Apple M1 Pro
	Graphics card #0 vendor: Apple (0x106b)
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: unknown
	Memory slot #0 capacity (MB): 0.00
	Memory slot #0 clockSpeed (GHz): 0.00
	Memory slot #0 type: unknown
	Virtual memory max (MB): 36864.00
	Virtual memory used (MB): 28705.27
	Swap memory total (MB): 4096.00
	Swap memory used (MB): 3519.44
	JVM Flags: 7 total; -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		deeperdarker: Deeper and Darker 1.1.6
			customportalapi: Custom Portal Api 0.0.1-beta54-1.19
			paragon: Paragon 3.0.2
				blue_endless_jankson: jankson 1.2.1
				com_moandjiezana_toml_toml4j: toml4j 0.7.2
				org_yaml_snakeyaml: snakeyaml 1.27
		fabric-api: Fabric API 0.76.0+1.19.2
			fabric-api-base: Fabric API Base 0.4.15+8f4e8eb390
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.14+93d8cb8290
			fabric-biome-api-v1: Fabric Biome API (v1) 9.1.1+16f1e31390
			fabric-block-api-v1: Fabric Block API (v1) 1.0.2+e415d50e90
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.25+cafc6e8e90
			fabric-client-tags-api-v1: Fabric Client Tags 1.0.5+b35fea8390
			fabric-command-api-v1: Fabric Command API (v1) 1.2.16+f71b366f90
			fabric-command-api-v2: Fabric Command API (v2) 2.2.1+413cbbc790
			fabric-commands-v0: Fabric Commands (v0) 0.2.33+df3654b390
			fabric-containers-v0: Fabric Containers (v0) 0.1.41+df3654b390
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.5.2+7c6cd14d90
			fabric-convention-tags-v1: Fabric Convention Tags 1.3.0+4bc6e26290
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.8+aeb40ebe90
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 5.3.8+413cbbc790
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.35+0d0f210290
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.4+9244241690
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.34+562bff6e90
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.36+df3654b390
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.24+b6b6abb490
			fabric-item-api-v1: Fabric Item API (v1) 1.6.6+b7d1888890
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.39+9244241690
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.25+5c4fce2890
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.23+df3654b390
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.4+1b46dc7890
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.13+83a8659290
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.16+9e7660c690
			fabric-message-api-v1: Fabric Message API (v1) 5.0.7+93d8cb8290
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.24+33fbc73890
			fabric-models-v0: Fabric Models (v0) 0.3.21+c6af733c90
			fabric-networking-api-v1: Fabric Networking API (v1) 1.2.11+10eb22f490
			fabric-networking-v0: Fabric Networking (v0) 0.3.28+df3654b390
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 4.2.2+d8ef690890
			fabric-particles-v1: Fabric Particles (v1) 1.0.14+4d0d570390
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.1+413cbbc790
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.32+9244241690
			fabric-renderer-api-v1: Fabric Renderer API (v1) 1.2.1+1adbf27790
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.8.0+1adbf27790
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.24+df3654b390
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.19+6e0787e690
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.11+4d0d570390
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.27+df3654b390
			fabric-rendering-v1: Fabric Rendering (v1) 1.12.1+d8ef690890
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.1.2+aae9039d90
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.8.4+edbdcddb90
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.32+4d0d570390
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.7+1cc24b1b90
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.2+c4f28df590
			fabric-textures-v0: Fabric Textures (v0) 1.0.24+aeb40ebe90
			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.1.6+413cbbc790
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.3.3+08b73de490
		fabricloader: Fabric Loader 0.14.18
		fpsdisplay: FPS-Display 1.5.0+1.19
			cloth-config: Cloth Config v6 7.0.69
				cloth-basic-math: cloth-basic-math 0.6.1
		geckolib3: Geckolib 3.1.20
			com_eliotlash_mclib_mclib: mclib 19
			com_eliotlash_molang_molang: molang 19
		iris: Iris 1.5.2
			io_github_douira_glsl-transformer: glsl-transformer 2.0.0-pre9
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.11.1
		java: OpenJDK 64-Bit Server VM 17
		lithium: Lithium 0.11.1
		malilib: MaLiLib 0.13.0
		minecraft: Minecraft 1.19.2
		skinlayers: 3d Skin Layers 1.5.2-mc1.19.1
		sodium: Sodium 0.4.4+build.18
			org_joml_joml: joml 1.10.4
		sound_physics_remastered: Sound Physics Remastered 1.19.2-1.0.18
		tweakeroo: Tweakeroo 0.14.3
		twilightforest: The Twilight Forest 4.2.335
			cardinal-components-base: Cardinal Components API (base) 5.0.1
			cardinal-components-entity: Cardinal Components API (entities) 5.0.1
			com_google_code_findbugs_jsr305: jsr305 3.0.2
			forgeconfigapiport: Forge Config API Port 4.1.4
				com_electronwill_night-config_core: core 3.6.5
				com_electronwill_night-config_toml: toml 3.6.5
			here-be-no-dragons: Here be no Dragons! 1.0.0
			javax_annotation_javax_annotation-api: javax.annotation-api 1.3.2
			mm: Manningham Mills 2.3
			porting_lib: Porting Lib 2.1.727+1.19.2
				com_github_llamalad7_mixinextras: MixinExtras 0.1.1
				forge_tags: Porting Lib Tags 3.0
				porting_lib_accessors: Porting Lib Accessors 2.1.727+1.19.2
				porting_lib_attributes: Porting Lib Attributes 2.1.727+1.19.2
				porting_lib_base: Porting Lib Base 2.1.727+1.19.2
				porting_lib_common: Porting Lib Common 2.1.727+1.19.2
				porting_lib_constants: Porting Lib Constants 2.1.727+1.19.2
				porting_lib_entity: Porting Lib Entity 2.1.727+1.19.2
				porting_lib_extensions: Porting Lib Extensions 2.1.727+1.19.2
				porting_lib_fake_players: Porting Lib Fake Players 2.1.727+1.19.2
				porting_lib_lazy_registration: Porting Lib Lazy Register 2.1.727+1.19.2
				porting_lib_model_generators: Porting Lib Model Generators 2.1.727+1.19.2
				porting_lib_model_loader: Porting Lib Model Loader 2.1.727+1.19.2
				porting_lib_models: Porting Lib Models 2.1.727+1.19.2
				porting_lib_networking: Porting Lib Networking 2.1.727+1.19.2
				porting_lib_obj_loader: Porting Lib Obj Loader 2.1.727+1.19.2
				porting_lib_transfer: Porting Lib Transfer 2.1.727+1.19.2
				serialization_hooks: Serialization Hooks 0.3.26
			reach-entity-attributes: Reach Entity Attributes 2.3.0
		xaerominimap: Xaero's Minimap 23.3.2
		xaeroworldmap: Xaero's World Map 1.29.4
	Loaded Shaderpack: ComplementaryReimagined_r2
		Profile: HIGH (+4 options changed by user)
	NEC status: No NEC detected
	Server Running: true
	Player Count: 1 / 8; [class_3222['carrotysoup'/234, l='ServerLevel[New World]', x=-766.12, y=103.00, z=-307.73]]
	Data Packs: vanilla, Fabric Mods
	World Generation: Stable
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Launched Version: fabric-loader-0.14.18-1.19.2

**Comment by NewJumper** [comment]
note to devs: error is related to sculk snapper animations

**Comment by Pedro270707** [comment]
GeckoLib no longer required
