### ISSUE TITLE
Only load compat recipes if mods are present.

### ISSUE THREAD

**Issue by MindBrain27** [KyaniteMods/DeeperAndDarker#153]
You have recipes involving Immersive Engineering, Mekanism, Create, Etc. They should only be active if the mod is loaded, otherwise the logs get spammed with 200+ recipes that are invalid because the dependency is missing. When trying to make modpacks the extra spam in the logs is incredibly annoying.

I believe 244 of these 246 are from Deeper & Darker, all from this issue. They also seem to not be removable using KubeJs either.

![deeperdarker1](https://user-images.githubusercontent.com/74363414/230794509-bc7aed6d-3ca4-4fc7-b285-37bcff756c2f.PNG)
![deeperdarker2](https://user-images.githubusercontent.com/74363414/230794607-5df011ef-ce7a-415d-891b-1fb0d58d7139.PNG)

I know some mods only load recipes if a certain tag is not empty, something like that may work.

**Comment by SiverDX** [comment]
I use https://www.curseforge.com/minecraft/mc-mods/log-begone to get rid of those messages

My messages looked like this (+ stacktrace):
```
[08:40:35] [Render thread/ERROR]: Parsing error loading recipe mekanism:enriching/conversion/gloomslate/tiles_to_bricks
com.google.gson.JsonSyntaxException: Invalid or unsupported recipe type 'mekanism:enriching'
```

After I modified the config `logbegone.toml` to this

```
phrases = ["the_aether", "Parsing error loading recipe mekanism"]
```

the messages were gone

**Comment by nitrodynamite18** [comment]
This has been fixed, but the fix has not been released just yet. We will try to release a hotfix before the next update.
