### ISSUE TITLE
Sounds have been broken for 4 months...

### ISSUE THREAD

**Issue by iron431** [KyaniteMods/DeeperAndDarker#154]
**Mod Version**: 1.1.6

**Mod Loader**: forge

**Description**:
Sounds registration appears in the logs, but something seems severely broken as no sounds play in game, and they don't actually appear to be loading (/playsound reveals no sounds under the deeperdarker namespace)

**To Reproduce**:
1. play game. 
2. no sound.

**Additional context**:
I don't mean to be a dick but this makes the mod borderline unplayable in my opinion.

**Comment by NewJumper** [comment]
sounds fixed in upcoming Deeper Darker v1.2.0 update
