### ISSUE TITLE
Warden does not drop Hearth or actually nothing other than Catalyst

### ISSUE THREAD

**Issue by M4RK0wasntavalible** [KyaniteMods/DeeperAndDarker#155]
**Mod Version**: x.xx.xx

**Mod Loader**: forge/fabric/both

**Description**:
Explanation of what the bug is doing, versus what the intended feature is supposed to be.

**To Reproduce**:
2. Click on '...'
3. Scroll down to '...'

**Screenshots**:

**Additional context**:
Add any other context about the problem here: crash reports, logs, and any other details.

**Comment by nitrodynamite18** [comment]
@M4RK0wasntavalible Please fill out the form properly, as well as include any other mods or data packs you were using.

**Comment by CSMMaster** [comment]
Mod Version: 1.6.1 (most recent)

Mod Loader: Fabric

Description: Have tried killing the Warden Several Times with no drops from this mod aside from the skulk catalyst

To Reproduce:
No error code was presented by the Client or Server Side logs

Additional Context:
I had WardenLoot and WardenTools mods installed, as well. Both were dropping loot as expected when the Warden was killed. Both have been removed (including their related config files), client/server restarted, and the only impact is that the Warden drops a single skulk catalyst when killed.

I do hope there is a fix as I am excited to release a new modpack with this epic mod included :)

**Comment by CSMMaster** [comment]
Following up on this bug. Has the Warden drops issue been looked into?

**Comment by NewJumper** [comment]
Warden properly drops the heart in the upcoming Deeper Darker v1.2.0 update for forge. Will have to check for fabric

**Comment by crandalj** [comment]
Works fine on the deeperdarker-fabric-1.20-1.2.0.jar
