### ISSUE TITLE
Server crashing upon entering portal 

### ISSUE THREAD

**Issue by BiggZee** [KyaniteMods/DeeperAndDarker#156]
**Mod Version**: 1.19.2

**Mod Loader**: fabric

**Description**:
Server seems to crash every time some attempts to enter a portal. 

**To Reproduce**:
1. Enter portal

**Screenshots**:

**Additional context**:
[crash-2023-04-19_22.28.12-server.txt](https://github.com/KyaniteMods/DeeperAndDarker/files/11278706/crash-2023-04-19_22.28.12-server.txt)

**Comment by Pedro270707** [comment]
I believe this issue was fixed as Custom Portal API was updated.
