### ISSUE TITLE
Can't run because it's saying geckolib3 is missing yet it is downloaded, no matter the version.

### ISSUE THREAD

**Issue by Stanlyhalo** [KyaniteMods/DeeperAndDarker#158]
**Mod Version**: 1.19.4

**Mod Loader**: fabric

**Description**:
Trying to play with this mod, and it's asking for geckolib3 3.1.14 or later to be installed, I've tried to install any version of Gecko Lib from 3.0.x to 4.0.x and it doesn't work, and also tried to look for 3.1.14, but it doesn't exist.

Also, I use prism launcher, which has never had any other issues with dependencies.

**To Reproduce**:
1. Download Deeper and Darker.
2. Download GeckoLib
3. Try to launch (with the other fabric dependencies)
4. Launch Error

**Screenshots**:
![image](https://user-images.githubusercontent.com/36088749/235383280-957362a5-8b25-4148-a86f-9e4f11951d08.png)
![image](https://user-images.githubusercontent.com/36088749/235383289-bcd78040-0c2b-493d-8b65-d2fb6c1a0beb.png)

**Comment by Pedro270707** [comment]
GeckoLib is no longer required
