### ISSUE TITLE
Server crash version 1.19.2

### ISSUE THREAD

**Issue by xXjojojXx** [KyaniteMods/DeeperAndDarker#159]
**Mod Version**:
1.19.2

**Mod Loader**: forge

[crash-2023-05-06_15.17.54-server.txt](https://github.com/KyaniteMods/DeeperAndDarker/files/11412452/crash-2023-05-06_15.17.54-server.txt)

our server crashes see log

**Comment by NewJumper** [comment]
This may have been fixed in the upcoming Deeper Darker v1.2.0 update. Will need some testing.
