### ISSUE TITLE
caused by a ClassCastException in the SculkSnapperEntity.tick()

### ISSUE THREAD

**Issue by jaynotgay** [KyaniteMods/DeeperAndDarker#160]
Mod Version 1.19.2

Mod Loade: /fabric/

Description:
The crash report indicates that the issue is caused by a ClassCastException in the SculkSnapperEntity.tick() method from the deeperdarker mod. The problematic line is SculkSnapperEntity.java:130.

It seems that the mod is trying to cast a net.minecraft.util.registry.RegistryKey object to a java.util.List, which is not allowed.

To Reproduce
1. Go to deeperdarker 
2. taim  SculkSnapperEntity
3. Scroll down to '...'
https://mclo.gs/VM0UnwP

**Comment by Pedro270707** [comment]
Should be fixed
