### ISSUE TITLE
Bug - Missing PNG for signs/echo.png

### ISSUE THREAD

**Issue by Yourname942** [KyaniteMods/DeeperAndDarker#163]
**Mod Version**: 1.1.6

**Mod Loader**: 
Forge 43.2.8
Minecraft 1.19.2

**Description**:
I just create a new world (or go into an existing one) and I get an error saying that this is missing a texture:

**To Reproduce**:
1. open curseforge app
2. create a new profile
3. Minecraft 1.19.2
4. Forge 43.2.8
5. Download JEI
6. Download Deeper and Darker
7. launch the game
8. create a new world (creative/ hard)
9. enter the world
10. close the game
_observe that the mod has a missing texture_

**Screenshots**:
![image](https://github.com/KyaniteMods/DeeperAndDarker/assets/58750222/a424182a-56aa-402f-8d8a-33ba3e9f0399)

**Additional context**:
latest log: https://paste.ee/p/dLXQK

**Comment by NewJumper** [comment]
If the texture works in-game, you can ignore the error message. This error message is no longer apparent in the next update.
