### ISSUE TITLE
Echo Boat Crashes game and corrupts world. (Severe Issue)

### ISSUE THREAD

**Issue by NolanHewitt** [KyaniteMods/DeeperAndDarker#164]
**Mod Version**: 1.1.6

**Mod Loader**: Fabric

**Description**:
Placing the Echo Boat instantly crashes the game and causes your world to not be possible to open again without uninstalling the mod.

**To Reproduce**:
1. Place the Echo Boat
2. Crash

**Comment by gamma-02** [comment]
This is indeed a bug, it has to do with a call to DDBoat$Type.getItem not having a null check.

whee

**Comment by gamma-02** [comment]
Do you have a crash report of this?

**Comment by NolanHewitt** [comment]
> Do you have a crash report of this?

Yes.
[crash-2023-06-04_01.46.50-client.txt](https://github.com/KyaniteMods/DeeperAndDarker/files/11644904/crash-2023-06-04_01.46.50-client.txt)
