### ISSUE TITLE
Sculk Snapper mob crashes game when i try to load in.

### ISSUE THREAD

**Issue by RiskierXenx** [KyaniteMods/DeeperAndDarker#166]
**Mod Version**: v20.5 (playing the Medieval Minecraft mod by SHXRKIE)

**Mod Loader**: fabric

**Description**:
Whenever I loaded into the deeper dark realm it ran fine but as i entered a new biome it crashed whenever i saw a sculk snapper. To make sure it was the sculk snapper i spawned one in tamed it, and when i did it, it crashed and i can't seem to be able to kill it. Whenever i strike at it, it doesn't take any damage and after a few seconds my game crashes. I can't use a command block or anything to see if i could kill it that way because i don't get enough time before it crashes. I can't even teleport away because it acts like a pet and teleports to you if your far away.

**To Reproduce**:
1. Find one naturally or Spawn one in
2. Tame it
3. After a few seconds watch and see if it crashes for you

**Screenshots**:
(i couldn't get any because i can't even load in now)

**Comment by Pedro270707** [comment]
Should be fixed
