### ISSUE TITLE
Need Paragon to work

### ISSUE THREAD

**Issue by Inverseder** [KyaniteMods/DeeperAndDarker#168]
**Mod Version**:1.1.16 on 1.19.2

**Mod Loader**: forge

**Description**:
I want to play with the mod but when I install it with curseforge client, it says to me it needs "paragon" to work but i can't find any mod named like that on curseforge

[main/ERROR]: Missing or unsupported mandatory dependencies:
	Mod ID: 'paragon', Requested by: 'deeperdarker', Expected range: '[2.0.0,)', Actual version: '[MISSING]'

**Comment by JDtheHutt** [comment]
It's only available on Modrinth.  A lot of mod authors have dropped Curseforge recently and you commonly have to go between the two to get stuff working.  Not a fault of this mod, just a divide in the modding ecosystem, especially when it comes to dependencies.

**Comment by NewJumper** [comment]
You can fix it by downloading Paragon from Modrinth and putting the jar in your mods folder.
Future Deeper Darker versions will not be using Paragon. If you wish to use Paragon via CurseForge, I would suggest asking the Paragon devs (in the discord or creating an issue on their GitHub).
