### ISSUE TITLE
Warden doesn't drop "Heart of the Deep" when killed.

### ISSUE THREAD

**Issue by NotchApple1234** [KyaniteMods/DeeperAndDarker#171]
1.1.6

forge

The main problem is see so far is them on death the warden doesn't drop the heart of the deep. I have killed the warden many times, sometimes even in creative to see if it works.

2. Click on '...'
3. Scroll down to '...'
(I don't understand that part before this so I'm going to leave it blank.)
**Screenshots**:
Can't really show nothing
**Additional context**:
If you can fix this as soon as possible please, it would be great.

**Comment by nitrodynamite18** [comment]
Check if any other mods or data packs change Warden drops.

**Comment by XAgent1990** [comment]
Use REI Mod to see the drops of the warden. You should be able to see which mod causes the inconsistency. I had this problem myself and easily solved it by overwriting its drops with my datapack.

**Comment by NewJumper** [comment]
Deeper Darker v1.2.0 is expected to fix this. If the issue is not fixed, it is likely due to another mod overriding the Warden's loottable entirely.
