### ISSUE TITLE
Incompatible With Show Me Your Skin

### ISSUE THREAD

**Issue by PolyframeX** [KyaniteMods/DeeperAndDarker#176]
**Mod Version**: 1.1.6

**Mod Loader**: Fabric

**Description**:
Show Me Your Skin allows for armor to be transparent / hidden in a config, all armor in DeeperAndDarker does not work with this mod

**To Reproduce**:
1. Download both Show me your skin and DeeperAndDarker
2. Wear any elytra/armor from DND
3. Set armor to be transparent / hidden
4. See the bug

**Screenshots**:
![image](https://github.com/KyaniteMods/DeeperAndDarker/assets/80133652/02801bd2-d63e-4b3f-9ced-24fd65432f13)

**Note:**
It's would make sense if transparency is not possible, but it would be nice to allow for hiding the armor set still.

**Comment by Pedro270707** [comment]
Deeper and Darker is now compatible with Show Me Your Skin!
![2023-10-19_19 20 03](https://github.com/KyaniteMods/DeeperAndDarker/assets/89267077/f9b21abf-cc3d-4ec6-846b-c3b30b3e1d32)
