### ISSUE TITLE
Ore double drop rate do not apply for Copper, Lapis and Redstone

### ISSUE THREAD

**Issue by XAgent1990** [KyaniteMods/DeeperAndDarker#177]
**Mod Version**: 1.1.6

**Mod Loader**: fabric

**Description**:
Copper, Redstone,  and Lapis Ore do not drop double. Like the other ores they only drop 1-3 of their resource like the other ores, which is less than the natural drops of them in the overworld.
I "fixed" this by overwriting the Loot Table of those blocks with the apropriate Droprate, but it would be nice if it could be officially fixed.
Copper currently is 1-3, should be 2-12
Lapis currently is 1-3, should be 4-22
Redstone currently is 1-3, should be 4-14

**To Reproduce**:
Break ore ^^

**Screenshots**:
Copper Loot Table as example:
![image](https://github.com/KyaniteMods/DeeperAndDarker/assets/12500926/e4d8b112-6b3b-4cb8-8c15-f58718c603e3)

**Comment by XAgent1990** [comment]
Copper currently is 1-3, should be 2-12
Lapis currently is 1-3, should be 4-22
Redstone currently is 1-3, should be 4-14

**Comment by NewJumper** [comment]
ore loottables updated in v1.2.0
