### ISSUE TITLE
Portal only lit from bottom

### ISSUE THREAD

**Issue by SpoderMan3288** [KyaniteMods/DeeperAndDarker#18]
Portal can only be lit from the bottom

**Comment by NewJumper** [comment]
do we possibly know where this is originating from?

**Comment by nitrodynamite18** [comment]
Not a clue, if I'm being honest. I believe it to be originating in the DeepHeartItem.java file.

**Comment by NewJumper** [comment]
Just confirmed, the error is most definitely NOT from `DeepHeartItem`. I'm 95% sure the issue is coming from `OthersidePortalBlock`
