### ISSUE TITLE
Create lava diving armor support

### ISSUE THREAD

**Issue by rfwn** [KyaniteMods/DeeperAndDarker#180]
Create mod offers an armor set named diving netherite armor that allows players to breathe and see under lava.
This diving gear needs only a diving helmet and a netherite backtank. It also requires basic netherite pants to function. 
However with warden pants, This doesn't seem to work, even though the armor is marked as fire resistant and also it is made by upgrading netherite armor. I think it would make more sense if the warden pants would make the player lava resistant, meanwhile achieving it's speed effect. The workaround over this is simple. In create mod source files you can see there's a check for the armor if it is netherite or not (create.content.equipment.armor.NetheriteDivingHandler.java).
So adding warden pants, or boots to this if clause, would make this happen.

**Comment by nitrodynamite18** [comment]
We will look into adding this!

**Comment by nitrodynamite18** [comment]
The current implementation of the Netherite Diving Helmet and Tank makes it impossible for the Warden armor to work with the items given it checks the armor's material, which for the Warden gear is not Netherite. I have opened a suggestion on Create's GitHub page for them to add a tag or another possible workaround.
