### ISSUE TITLE
[1.19.2] Create Compatability

### ISSUE THREAD

**Issue by DelviousCrafts** [KyaniteMods/DeeperAndDarker#181]
**Mod Version**: 1.1.6

**Mod Loader**: Forge

**Description**:
Most recent version of Create mod has changed the name of crushed ore to crushed_raw_copper, etc. instead of crushed_copper_ore causing incompatibility with ore processing with this mod. 

**To Reproduce**:
1. install create alongside deeper and darker
2. load game
3. see processing of sculk ores are no longer possible using create

**Screenshots**:

**Additional context**:
Create: 0.5.1.c

**Comment by NewJumper** [comment]
fixed in 742cf0d07ab5d9437e91ed6bd32c55882726f7e7
