### ISSUE TITLE
the Elytra no longer propels into the Trinkets slot.

### ISSUE THREAD

**Issue by SystAmynna** [KyaniteMods/DeeperAndDarker#182]
**Mod Version**: 1.1.6 (mc 1.19.2)

**Mod Loader**: fabric

**Description**:
Hello, I'm currently using the mod in a modpack of my creation (under fabric) with Trinkets, when I equip the mod's Elytra in Elytra's slot, it works like a standard Elytra and no longer propels me. Did I miss something?

**To Reproduce**:
1. Use "Trinkets" + "Elytra Slot"
2. Equip Elytra on Elytra Slot
3. Try to flight
4. Elytra work just like normal Elytra

**Comment by NolanHewitt** [comment]
Can confirm this is true, the boost part of the elytra doesn't work for me unless its in the chestplate armor slot.

**Comment by Pedro270707** [comment]
Soul Elytra no longer boost in 1.2.1
