### ISSUE TITLE
Infested Sculk doesn't spawn any creature

### ISSUE THREAD

**Issue by gusbaruc** [KyaniteMods/DeeperAndDarker#185]
**Mod Version**: 1.1.6
**Mod Loader**: forge 43.2.21
**Minecraft Version**: 1.19.2

**Description**:
The Infested Sculk block doesn't spawn any mob when broken. It just drop xp like a regular sculk block. I guess breaking it should spawn a Sculk Leech, shouldn't it?

**To Reproduce**:
1. Find a Infested Sculk block
2. Break it
3. See error

**Screenshots**:
N/A

**Additional context**:
N/A

**Comment by NewJumper** [comment]
added in 7b0d8266cc96a4bfaf34293091c1febe7a6c1b09
