### ISSUE TITLE
the other structures crashing server and skulker familiar crashing players 

### ISSUE THREAD

**Issue by PPRJACKCHEESE** [KyaniteMods/DeeperAndDarker#186]
im the latest version of ATM8 and im playing on a friend server, i was entering a structure in the other that was a pyramid and another one that looked like a 4 tower structure, im assuming the amount of entites that spawned in crashed our server but it seems to be crashing everytime we enter a building there. our latest issue is summoning a familiar that just crashes anyone that is in chunk distance to it. this is the code we get everytime we crash 
Error: java.lang.NullPointerException: Cannot invoke "net.minecraft.world.entity.LivingEntity.m_20270_(net.minecraft.world.entity.Entity)" because the return value of "com.kyanite.deeperdarker.registry.entities.custom.SculkSnapperEntity.m_21826_()" is null

these two problems are preventing us from progressing further into the mod. it really needs to be looked at ASAP incase anyone else is having the issue or has yet to encounter it

**Comment by PPRJACKCHEESE** [comment]
update: the chunk where the familiar was corrupted my server and i had to restart all progress due to this bug.

**Comment by NewJumper** [comment]
yea unfortunately the sculk snapper had some broken code that caused a crash. luckily, in the upcoming update, the bug is fixed!
