### ISSUE TITLE
DIMENSION ID MISSING ?

### ISSUE THREAD

**Issue by Z1LEX0** [KyaniteMods/DeeperAndDarker#187]
**Description**:
ADDING OPTION TO MAKE A CUSTOM DIMENSION ID OR ADD IT TO SHADERS
**Additional context**:
Im really frustrated about not being able to find out a dimension id idk if this really is your problem but it should be added so people have a much nicer way of customizing it

**Comment by NewJumper** [comment]
not sure what you mean by dimension id. if you're talking about the dimension name, its `otherside`
