### ISSUE TITLE
Chunk loading issue

### ISSUE THREAD

**Issue by Devilswarchild** [KyaniteMods/DeeperAndDarker#188]
**Mod Version**: deeperdarker-forge-1.20.1-1.2.0.jar
**Mod Loader**: forge 47.1.3
MC version 1.20.1

**Description**:
biomes in the insideout dimensions are not rendering properly and when spawning the sculk snapper game sometimes crashes or doesn't. but its evidently clear something has broken with the transition to 1.20.x.

**To Reproduce**:
1. Go to insideout dimension and try to go over a couple hundred blocks in any given direction
2. see error and all associated ticks (just halts)

**Screenshots**:

![image](https://github.com/KyaniteMods/DeeperAndDarker/assets/27385258/0cba6a18-25df-4860-aba6-922126c7a579)
![image 2](https://github.com/KyaniteMods/DeeperAndDarker/assets/27385258/bb6efb8a-fa96-4b12-8edd-b5a01b4a8575)
![image 3](https://github.com/KyaniteMods/DeeperAndDarker/assets/27385258/fc7c8385-7061-4e16-9eb4-3b115e2bdf54)

**Additional context**:
here logs from two of my dev members for my modpack MineColonies: Dimensional Adventure

[(Hitherix) debug.log](https://github.com/KyaniteMods/DeeperAndDarker/files/12403319/Hitherix.debug.log) (https://mclo.gs/ZSWu1Xm for easier reading)
[(Hitherix) latest.log](https://github.com/KyaniteMods/DeeperAndDarker/files/12403320/Hitherix.latest.log) (https://mclo.gs/Y0FqqMa for easier reading)

[(SeantheSheep) debug.log](https://github.com/KyaniteMods/DeeperAndDarker/files/12403332/SeantheSheep.debug.log) (https://mclo.gs/R6fSmEh for easier reading)
[(seanthesheep) latest.log](https://github.com/KyaniteMods/DeeperAndDarker/files/12403343/seanthesheep.latest.log) (https://mclo.gs/mrs2l8C for easier reading)
[(seanthesheep)launcher_log.txt](https://github.com/KyaniteMods/DeeperAndDarker/files/12403344/seanthesheep.launcher_log.txt) (https://mclo.gs/ipxueg1 for easier reading)

**Comment by NewJumper** [comment]
Chunk loading is a known issue, but no one in the dev team, including me, don't really know what's causing it. We are still trying to find the cause

**Comment by Devilswarchild** [comment]
my main dev member says its something in the forest related biome of your mods dimension finding an entity it just doesnt like

**Comment by Devilswarchild** [comment]
cause he says as soon as whatever mob it is spawns the ticks just stop updating

**Comment by NewJumper** [comment]
nope its not entities causing it. We've tested on peaceful and it was still an issue. All we know is that its being caused by features (things that generate like vines, trees, ores, etc)

**Comment by EvieTheOwl** [comment]
It looks like the column feature is failing to generate. Specifically the `stretchToFloor` feature method. That's the only common link I could find between the 2 debug logs sent.

I wonder if it's stuck in an infinite loop trying to generate it because something changed in 1.20 that modified how stretchToFloor is called?

**Comment by EvieTheOwl** [comment]
Looks like an issue with this loop https://github.com/KyaniteMods/DeeperAndDarker/blob/69bc84fa5670a520c9e68e66edb64f569489b6fa/src/main/java/com/kyanite/deeperdarker/world/features/SculkStoneColumnFeature.java#L110C13-L113C14

**Comment by NewJumper** [comment]
ill look into it, thanks for pointing it out!

**Comment by EvieTheOwl** [comment]
Yep this is the issue. Been debugging and the issue is it can exit the bottom of the world if it doesn't find specified block within the if statement. You need to check for bedrock placement as well or check if y > 0 for lower placement and the opposite for upper.

  
<img width="904" alt="Screenshot 2023-10-08 at 16 56 35" src="https://github.com/KyaniteMods/DeeperAndDarker/assets/46009144/b2a829b9-d3ad-423a-a502-9647f36a1982">

You can see y = - (a very big number) here in the screenshot

**Comment by NewJumper** [comment]
5e4f20e does not seem to fix the issue.
load a world on this seed: -1125972046644107959
then go north

**Comment by EvieTheOwl** [comment]
Hmmm that's annoying ok. I'll test again

**Comment by EvieTheOwl** [comment]
I've flown out 10000 blocks north with that seed and no issues at all. I didn't update the Forge version so maybe that's why?

**Comment by NewJumper** [comment]
The chunk loading is not an issue on fabric, but it is on forge. It's not the columns that cause the issue

**Comment by EvieTheOwl** [comment]
> The chunk loading is not an issue on fabric, but it is on forge. It's not the columns that cause the issue

Really? I mean based on that debug trace it absolutely should be an issue for both platforms, it's an infinite loop.
It also stopped loading chunks on fabric when I tested it so it's definitely not a Forge only issue.

Tbh structures are very rarely platform specific as well so the chances it's a Forge only issue is incredibly low.

**Comment by NewJumper** [comment]
Not the column-loop issue, but the chunks-not-generating issue. Even with the infinite loop prevention, the chunks still refuse to load on forge.

**Comment by EvieTheOwl** [comment]
> Not the column-loop issue, but the chunks-not-generating issue. Even with the infinite loop prevention, the chunks still refuse to load on forge.

Oh I see ok. Just be absolutely sure the 2 aren't related because chunks failed to load on fabric as well because it got stuck in an infinite loop of trying to load them when it hit the column segment.

If it's a separate issue it should be relatively trivial to debug as well by pausing in debug mode when it happens. Unless it's not an issue with an infinite loop or deadlock which can be harder to solve.

**Comment by EvieTheOwl** [comment]
Yep there is an issue with the commit u made to the forge version: https://github.com/KyaniteMods/DeeperAndDarker/commit/a1eeb840afc3335bb88551b7d3d9ee268a0991aa?diff=split#r129754652

**Comment by NewJumper** [comment]
Oops! Did not even realize. Chunk loading is still an issue however.
same seed, same place

**Comment by EvieTheOwl** [comment]
> Oops! Did not even realize. Chunk loading is still an issue however. same seed, same place

Does it show anything in the debugger at all or nowt?
Maybe it's another structure generation issue?
