### ISSUE TITLE
Quilt crash on start

### ISSUE THREAD

**Issue by GitUser14975** [KyaniteMods/DeeperAndDarker#189]
**Mod Version**: 1.2.0
**Mod Loader**: quilt

**Description**:
When I try to run the game it crashes.

**Additional context**:
Crash log: https://gist.github.com/TenKotowsky/22a69ec24206951a2933028728eeb80f

**Comment by TrueDevron** [comment]
Also having this issue

**Comment by NolanHewitt** [comment]
Same here. Previous versions worked on quilt but this one doesn't.
[crash-2023-08-26_01.23.59-client.txt](https://github.com/KyaniteMods/DeeperAndDarker/files/12444710/crash-2023-08-26_01.23.59-client.txt)

**Comment by eristhea** [comment]
this is because the mod uses fabric internals, which is bad practice. please copy the mixin instead of using fabric's!

**Comment by XDom367** [comment]
@ix0rai how do I do that? Or does the dev have to fix it?

**Comment by XDom367** [comment]
Or does the dev have to?

**Comment by eristhea** [comment]
fixed this quick from the github web editor, should be fine once the PR is merged

**Comment by eristhea** [comment]
@Pedro270707 this is now fixed!

**Comment by Pedro270707** [comment]
Yes, I'll close it
