### ISSUE TITLE
Ancient Vase missing sounds!

### ISSUE THREAD

**Issue by DEAFG0AT** [KyaniteMods/DeeperAndDarker#190]
**Mod Version**: 1.19.2
**Mod Loader**: FABRIC

**Description**:
No sound when placing or breaking the Ancient Vase!

**To Reproduce**:
1. Enter the game.
2. Place or break an Ancient Vase.
3. Observe the lack of sound.

**Screenshots**:

https://github.com/KyaniteMods/DeeperAndDarker/assets/104733108/a9d66f6a-616d-4d80-8c7f-146b75fa614e

**Additional context**:
Breaking or placing the block DOES active sculk sensors.

**Comment by Pedro270707** [comment]
Fixed in 1.2.1
