### ISSUE TITLE
Crash when summoning a boat with /summon

### ISSUE THREAD

**Issue by GolfinhoVoador** [KyaniteMods/DeeperAndDarker#196]
**Mod Version**: 1.2.0
**Mod Loader**: forge

**Description**:
Summoning either of the boat entities crashes the game when using the summon command, other entities summon normally.

**To Reproduce**:
1. Open a world with cheats enabled, Preferably a new one that you dont care about since it will also softlock you.
2. Type "/summon deeperdarker:boat" or "/summon deeperdarker:chest_boat"
3. Your game will crash immediatelly.

**Additional context**:
_Tested without any other mods_
[Crash log](https://mclo.gs/rk4v932)

**Comment by GloomySenpai** [comment]
was this issue ever fixed?

**Comment by GolfinhoVoador** [comment]
> was this issue ever fixed?

It probably got fixed but they didnt build a new version yet

**Comment by GloomySenpai** [comment]
> > was this issue ever fixed?
> 
> It probably got fixed but they didnt build a new version yet

I see. Luckily in the crash logs it told me what cords the boat was at and I was in a server when it happened so I just summoned a bunch of TNT to destroy it. This allowed my client version to join without crashing.
