### ISSUE TITLE
Cant craft warden helmet

### ISSUE THREAD

**Issue by ochimmyo** [KyaniteMods/DeeperAndDarker#197]
cant craft warden helmet, my crafting table shows 3 options to put stuff in not 2, please help!! I have the deeper and darker mod pack for forge in my mods folder on minecraft, but i dont see any of the features of this pack.  please help

**Comment by NewJumper** [comment]
Could you provide a video or a screenshot?

**Comment by NewJumper** [comment]
Also, please follow proper bug reporting guidelines

**Comment by ochimmyo** [comment]
how do i find warden upgrade template?

**Comment by NewJumper** [comment]
they are found in ancient city chests
