### ISSUE TITLE
No Drops from Mobs

### ISSUE THREAD

**Issue by TheActualNez** [KyaniteMods/DeeperAndDarker#199]
**Mod Version**: 1.20.1
**Mod Loader**: Forge 47.0.35

**Description**:
Title says it all. I have removed all other mods and datapacks; issue has yet to be resolved. Wardens do not drop hearts, sculk centipedes only drop string, et cetera. I do not have the More Mob Heads datapack from Vanilla Tweaks, so that is not the issue. 

Wardens only drop catalysts, centipedes only drop string— issue is consistent with all Deeper & Darker mobs.

**To Reproduce**:
N/A. Simply not experiencing any mob drops, regardless of my modpack.

**Comment by NewJumper** [comment]
I was unable to recreate this

**Comment by Eon1g** [comment]
I too am having a similar issue in the most recent Fabric update.

Wardens will drop hearts, shards etc but, none of the mobs inside the Otherside will drop anything. I assumed the drop rate was low but, they refuse to drop anything but experience orbs.

**Comment by NewJumper** [comment]
For fabric, id suggest opening a new issue

**Comment by NewJumper** [comment]
Unable to recreate
