### ISSUE TITLE
Incompatible with Combatify

### ISSUE THREAD

**Issue by drown3d** [KyaniteMods/DeeperAndDarker#204]
**Mod Version**: 1.2.0
**Mod Loader**: fabric/quilt

**Description**:
Mod crashes on startup if Combatify is installed.

**To Reproduce**:
1. Install ([Quilted](https://modrinth.com/mod/qsl)) [Fabric API](https://modrinth.com/mod/fabric-api)
2. Install Deeper and Darker
3. Install [Combatify](https://modrinth.com/mod/combatify) and [owo-lib](https://modrinth.com/mod/owo-lib)
4. Attempt to launch the game
5. See crash report

**Additional context**:
[Crash report](https://pastebin.com/E9tk6vKA)

**Comment by Pedro270707** [comment]
Already fixed, completely unrelated to Combatify or owo-lib
