### ISSUE TITLE
Can't strip Echo Logs witth an axe.

### ISSUE THREAD

**Issue by Snedglow** [KyaniteMods/DeeperAndDarker#205]
**Mod Version**: 1.1.6
**Mod Loader**: forge

**Description**:
Can't strip echo logs by the "normal" method.  I've tried several modded methods in the pack I play ( Valhelsia 5) and the only way that works seems to be the cutting board from Farmers Delight.

**To Reproduce**:
1. Place log no grouond
2. Right click with axe to strip
3. Log no strip

**Screenshots**:

**Additional context**:
Add any other context about the problem here: crash reports, logs, and any other details.

**Comment by NewJumper** [comment]
Fixed in 1.2.0
