### ISSUE TITLE
Summoning boats crashes the game

### ISSUE THREAD

**Issue by GloomySenpai** [KyaniteMods/DeeperAndDarker#206]
Mod Version: 1.20.1
Mod Loader: forge

Description:
Summoning either of the boat entities crashes the game when using the summon command, other entities summon normally.

To Reproduce:

    Open a world with cheats enabled, Preferably a new one that you dont care about since it will also softlock you.
    Type "/summon deeperdarker:boat" or "/summon deeperdarker:chest_boat"
 #196   Your game will crash immediatelly.

**Comment by NewJumper** [comment]
#196
