### ISSUE TITLE
Reinforced Echoshard Recipe is Incorrect

### ISSUE THREAD

**Issue by Seraphim1138** [KyaniteMods/DeeperAndDarker#209]
**Mod Version**: 1.20.x
**Mod Loader**: fabric

the recipe for reinforced echhoshards is incorrect versus what the wiki says is the recipe

![2023-10-02_19 31 12](https://github.com/KyaniteMods/DeeperAndDarker/assets/22765854/856d6598-e302-4d28-97ca-2031e709c433)

**Comment by NewJumper** [comment]
No? where exactly are you checking for the wiki?
