### ISSUE TITLE
Let the Portal be difference sizes. 

### ISSUE THREAD

**Issue by ebaystudio** [KyaniteMods/DeeperAndDarker#210]
I have a datapack that adds allot to the ancient cities but the portals are 2 blocks taller and 1 block longer then vanilla and for some reason I cant open the D&D portals unless they are exactly the same size as vanilla. 

Maybe make it the same as nether portals with a min and max size..

**Comment by NewJumper** [comment]
For forge or fabric? This shouldn't be an issue on forge

**Comment by ebaystudio** [comment]
It is on Fabric 1.19.2

**Comment by Pedro270707** [comment]
I've tried adding this before, maybe if I try again it will work

**Comment by ebaystudio** [comment]
So is is it going to be address in 1.19.2 fabric if its already fixed in forge?

**Comment by Pedro270707** [comment]
Forge uses a completely different system from Fabric

**Comment by Pedro270707** [comment]
Addressed in 1.2.1, now you will be able to create any portal with a frame equal to or larger than 10x6
