### ISSUE TITLE
Mobs don’t drop loot

### ISSUE THREAD

**Issue by wheresmyshadow** [KyaniteMods/DeeperAndDarker#212]
**Mod Version**: 1.2.0
**Mod Loader**: fabric

**Description**:
Original mobs and the Warden don’t drop any of the loot

**To Reproduce**:
Kill Warden, heart should drop 100% of the time but doesn’t. Enter the Otherside, mobs don’t drop any loot upon death.

**Comment by Pedro270707** [comment]
I killed the warden and it seems to be dropping everything, so I think another mod/datapack is replacing its loot table. Deeper and Darker mobs not dropping anything has been fixed in 1.2.1
