### ISSUE TITLE
server log spamming and darkness wont apply to player after entered the otherside

### ISSUE THREAD

**Issue by liangmoe** [KyaniteMods/DeeperAndDarker#218]
**Mod Version**: 1.19.2
**Mod Loader**: fabric

**Description**:
server log spamming "[Server thread/ERROR]: Recoverable errors when loading section [-22, 7, 65]: (Unknown registry key in ResourceKey[minecraft:root / minecraft:worldgen/biome]: deeperdarker:otherside_deeplands -> using default)" 
and darkness effect wont apply player after entered the otherside

**To Reproduce**:
1. Go to 'otherside'
2. bug happened

**Screenshots**:
[latest.log](https://github.com/KyaniteMods/DeeperAndDarker/files/13064542/latest.log)

**Additional co

https://github.com/KyaniteMods/DeeperAndDarker/assets/135343248/621e1578-89b1-4f87-8998-a3e809c90471

ntext**:

**Comment by NewJumper** [comment]
the otherside no longer applies darkness

**Comment by Pedro270707** [comment]
I believe this might be another mod using the wrong ID for the biome
