### ISSUE TITLE
Crash when placing Echo Signs. World becomes unloadable.

### ISSUE THREAD

**Issue by CinnYaBoi** [KyaniteMods/DeeperAndDarker#219]
**Mod Version**: 1.2.1
**Mod Loader**: forge

**Description**:
Game crashes when placing an Echo Sign, world becomes inaccesible (crashes when loading) unless Deeper And Darker is removed from mods. World then loads, but crashes again when placing an Echo Sign.

**To Reproduce**:
1.Install mods listed in the crashlog
2.Place down an Echo sign

**Screenshots**:
Giphy video demonstration:
https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExZXV5Mmp2cGExdjZ3YnliN3g0ODBzdzZrcmxxY2Q1aGlyN2dnZXRxMSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/HrsWadmsQErCTw4uoX/giphy.gif

**Additional context**:
Crash report pastebin: 
https://pastebin.com/Lcm8facE

**Comment by NewJumper** [comment]
~~What Minecraft version?~~
nvm, realized its 1.19

**Comment by CinnYaBoi** [comment]
yeah, 1.19.2
