### ISSUE TITLE
cannot invoke particle

### ISSUE THREAD

**Issue by Hebbywebby** [KyaniteMods/DeeperAndDarker#222]
**Minecraft Version**: 1.20.1
**Mod Version**: 1.2.1
**Mod Loader**: fabric

**Description**:
My multiplayer server has been experiencing multiple cases of the game downright crashing for every player on the server. This happens only when the mob "ShriekWorm" emerges from the ground, upon which the game will crash. Looking into the error screen, it seems to have to do something with the game being unable to invoke a particle effect produced by the ShriekWorm upon emerging from the ground.

**To Reproduce**:
1. Go to the new Dimension "Otherside"
2. Encounter Entity "ShriekWorm"
3. Get close enough to provoke the "ShriekWorm", and make it emerge from the ground
4. Game will crash shortly after

**Screenshots**:
![4d63c2793511305e18f956c0ae6e512c](https://github.com/KyaniteMods/DeeperAndDarker/assets/57565523/91638957-901e-4c98-9f4d-e9048868cc48)

**Additional context**:
I've tried to look up "Exit Code -1", but I've had no luck so far. If I'm missing something, or simply need to switch mod versions, please let me know!

**Comment by Pedro270707** [comment]
Send the crash report, "Exit Code -1" just means that something went wrong
