### ISSUE TITLE
Soul Elytra not auto boosting?

### ISSUE THREAD

**Issue by B1adereaper** [KyaniteMods/DeeperAndDarker#224]
**Minecraft Version**: 1.19.2
**Mod Version**: 1.2.2
**Mod Loader**: forge

**Description**:
Soul Elytra is not able to auto boost like previous update, firework boosting is disabled on my server so this item is the endgame movement fix and it is broken now?

**To Reproduce**:
Steps to reproduce the behaviour:
1. equip soul elytra item
2. Fly
3. Fall due to lack of auto boost

**Comment by Pedro270707** [comment]
It's not a bug, auto-boosting was removed
