### ISSUE TITLE
Error en la 1.19.1 (servidor crasheado)

### ISSUE THREAD

**Issue by dayanab26** [KyaniteMods/DeeperAndDarker#225]
**Minecraft Version**: 1.19.1
**Mod Version**: Probé con todas las versiones y ocurria el mismo error
**Mod Loader**: forge

**Description**:Me encuentro con mi servidor crasheado (no me deja iniciarlo) debido a que me sale un error descrito como "A fmlcore-1.19.1-42.0.9.jar le falta el archivo mods.toml" y "Falta la versión javafml del idioma java43, buscada por deepdarker-forge-1.1.1.jar, encontrada java42" no encuentro solución al error ya que los demas mods que uso no tienen que ver con el warden y tengo entendido que java42 es el usado en la versión 1.19.1.
**Screenshots**:
![image](https://github.com/KyaniteMods/DeeperAndDarker/assets/149269464/ad6de12d-986d-4ada-a647-b899e394b5c8)
De todas maneras dejo lista de los mods que empleo:
![image](https://github.com/KyaniteMods/DeeperAndDarker/assets/149269464/3ccee533-be03-4497-b68d-7fb4da8c8869)

**Comment by NewJumper** [comment]
use the updated version of deeper darker to see if the issue persists.
please translate to english!

**Comment by dayanab26** [comment]
Gracias por la respuesta!, Si probé ahora mismo hasta con la versión más actual para la 1.19.1 (osea la 1.1.6) e igualmente sigo con el error, me parece raro si fuera la única con este mismo problema y la traducción al español se dió por medio de google translate (no afecta el mod).

**Comment by NewJumper** [comment]
we recommend to use 1.19.2. we haven't backported recent updates to 1.19.1
