### ISSUE TITLE
Warden helmet bug with darkness effect

### ISSUE THREAD

**Issue by PartOfCheese** [KyaniteMods/DeeperAndDarker#226]
**Minecraft Version**: 1.20.1
**Mod Version**: 1.2.0
**Mod Loader**: fabric

**Description**:
Warden helmet doesn't remove darkness effect.

**To Reproduce**:
1. put on warden helmet
2. go to lost city
3. summon warden

**Screenshots**:
![image](https://github.com/KyaniteMods/DeeperAndDarker/assets/90419651/63394cec-c320-4d05-9be7-7f914fb7c765)

**Comment by PartOfCheese** [comment]
![image](https://github.com/KyaniteMods/DeeperAndDarker/assets/90419651/768b368b-4dca-438a-83d8-9d92be98d6b0)

**Comment by Pedro270707** [comment]
Fixed
