### ISSUE TITLE
[Suggestion] Add usage for Heart of the Deep, like crafting Warden Shield

### ISSUE THREAD

**Issue by chemlzh** [KyaniteMods/DeeperAndDarker#227]
**Description**:

Now Heart of the Deep is an unstackable item in Forge 1.20.1 version, and can be only used to open the Otherside portal. In addition, the Otherside portal generates at a low chance, therefore Heart of the Deep cannot be consumed in time, which means it will just fill in my chest and waste my space.

I think that it would be better to add another usage for Heart of the Deep. For example, you can use Heart of the Deep and other materials to craft Warden Shield. This kind of shield have a higher durability, and can block sonic boom attack for Warden. You know, the sonic boom attack cannot be absorb by armors or enchantments, and can hit through the blocks, therefore it's a dangerous move for player exploring deep dark biome or the Ancient City.

**Comment by Pedro270707** [comment]
The heart of the deep can now be used to craft the sonorous staff
