### ISSUE TITLE
Game Crashes when pressing E, says it crashes because its trying to load object deeperdarker:soul_elytra but cannot

### ISSUE THREAD

**Issue by camclerk** [KyaniteMods/DeeperAndDarker#229]
**Minecraft Version**: 1.20.1
**Mod Version**: 1.20.1
**Mod Loader**: forge

**Description**:
When I load in everything thing is fine until I press E to access inventory/crafting. Game completely crashes and the crash report says "The game crashed whilst rendering entity in world
Error: java.lang.NullPointerException: Registry Object not present: deeperdarker:soul_elytra"

**To Reproduce**:
1. load in
2. Press E
3. Game Crashes
4. Cry

**Screenshots**:
![Screenshot 2023-11-02 095034](https://github.com/KyaniteMods/DeeperAndDarker/assets/149670587/2fba737a-2563-4a9a-b341-56f33b5d4dfc)

**Additional context**:
n/a.

**Comment by NewJumper** [comment]
can you provide the full crash report

**Comment by NewJumper** [comment]
closed due to no response
