### ISSUE TITLE
Portal spawning on roof of Otherside

### ISSUE THREAD

**Issue by OMMorticia** [KyaniteMods/DeeperAndDarker#230]
**Minecraft Version**: 1.20.1
**Mod Version**: 1.2.2
**Mod Loader**: fabric

**Description**:
Portal is spawning in the bedrock above the dimension, making survival players unable to return from the otherside or explore the otherside.

**To Reproduce**:
1: Open portal
2: step through to Otherside

**Screenshots**:

![2023-11-03_13 12 37](https://github.com/KyaniteMods/DeeperAndDarker/assets/38755362/fd5e525a-bcce-4092-b4b0-1a21d8ca0677)

**Additional context**:
I do have other mods added, but none add dimensions, biomes, or enemies. No errors reported on console. issue happened both on server and in single player.

**Comment by Pedro270707** [comment]
Fixed in 1.2.3

**Comment by OMMorticia** [comment]
where/when will we be able to get 1.2.3? I only see 1.2.2 on curseforge but would be happy to get fabric 1.2.3 for 1.20.1 if it's up elsewhere! (thank you for the fast response also!)
