### ISSUE TITLE
Using Sculk Transmitter On An Unloaded Chest Allows You to Dupe Items

### ISSUE THREAD

**Issue by Cyberbit-7** [KyaniteMods/DeeperAndDarker#233]
**Minecraft Version**: 1.20.1
**Mod Version**: 1.2.3
**Mod Loader**: Fabric

**Description**:
When using the sculk transmitter outside of render distance of the chest, a message appears saying  "the linked block is missing or unloaded". However, the sculk transmitter menu still opens, allowing you to take items out. Critically, this dupes the item, as when returning to the chest or reopening the menu, the item still remains inside. Additionally, putting an item from your inventory into the menu will destroy it forever if you close the menu.

**To Reproduce**:
1. Link sculk transmitter to container
2. Travel outside render distance of container
3. Right-click sculk transmitter
4. Menu opens despite container being unloaded, allowing you to dupe items

**Comment by GioDM** [comment]
This is not only associated with fabric, same problem occurs on forge with version 1.2.1 of the mod.

**Comment by Pedro270707** [comment]
I believe this is fixed on Fabric

**Comment by NewJumper** [comment]
I haven't been able to replicate this on forge. Could you provide a video?

**Comment by Junnstoy** [comment]
@NewJumper @Pedro270707 
I also encountered this issue on fabric1.20.1 with mod1.2.3.
The game screen recording is as follows： [https://download.rbq.kr/?f=/debug/Base%20Profile%202024.03.14%20-%2019.49.04.01.mp4](url)
