### ISSUE TITLE
Warden pickaxe not forge Netherite mining level

### ISSUE THREAD

**Issue by Centrimonium** [KyaniteMods/DeeperAndDarker#235]
I just created the warden pickaxe out of god level netherite pick, and now it is essentially useless. 
I can't for the love of me find the config which handles the Warden Pickaxe mining level. Is it stored somewhere in the forge config and not in the DeeperAndDarker files??

**Comment by NewJumper** [comment]
It's higher than netherite. I am not sure what you mean, please provide more information (video or something)
