### ISSUE TITLE
Stalker not spawning

### ISSUE THREAD

**Issue by Shipmans-AGLA** [KyaniteMods/DeeperAndDarker#236]
**Minecraft Version**: 1.19.2
**Mod Version**: 1.2.3
**Mod Loader**: fabric

**Description**:
Stalker is not spawning when vases are broken, ive broken at least 3 stacks of vases and gotten no spawns. sculk leeches still spawn though. Most were placed by me in creative and then broken in survival, but i have also broken all vases in a temple in the deeper darker dimension and a friend of mine has broken all the vases of at least 3 temples and gotten no spawns.

**To Reproduce**:
1. Find ancient vases
2. Destroy a lot of them in survival mode
3. No stalkers spawn

**Screenshots**:

**Additional context**:
Modpack in use: https://www.curseforge.com/minecraft/modpacks/homeslicing
both me and my friend are using an indev version of this pack, not sure if it occurs on the public version.

**Comment by NewJumper** [comment]
intended, the stalker is a rare mob
