### ISSUE TITLE
non of the heart of warden drop when kill a warden 

### ISSUE THREAD

**Issue by DuongHoamh** [KyaniteMods/DeeperAndDarker#237]
**Minecraft Version**: 1.20.1
**Mod Version**: 1.2.1
**Mod Loader**: forge

**Description**:
Explanation of what the bug is and how it affects the game.

**To Reproduce**:
2. Click on '...'
3. Scroll down to '...'

**Screenshots**:

**Additional context**:
Add any other context about the problem here: crash reports, logs, and any other details.

**Comment by NewJumper** [comment]
Please properly fill out the bug report or else we will ignore this issue
