### ISSUE TITLE
The soul elytra no longer gives boosts

### ISSUE THREAD

**Issue by Poly-0000** [KyaniteMods/DeeperAndDarker#240]
**Minecraft Version**: 1.19.2
**Mod Version**: 1.2.3
**Mod Loader**: quilt

**Description**:
The soul elytra no longer gives boosts

**To Reproduce**:
Wear soul elytra and start flying

**Additional context**:
Tested this with no other mods present (not including quilted fabric API of course)

**Comment by NewJumper** [comment]
that is intentional
