### ISSUE TITLE
Game crash

### ISSUE THREAD

**Issue by isomd** [KyaniteMods/DeeperAndDarker#241]
I get a Sculk Transmitter and linked, when I point it, game crashed,

**Comment by NewJumper** [comment]
fill out the bug report properly

**Comment by isomd** [comment]
After I bound the workbench using the Sculk Transmitter and then exited the game, the next time I logged in, the game crashed when my mouse hovered over the Sculk Transmitter. This continued to happen until I removed the Sculk Transmitter using a command, after which everything returned to normal. Sculk Transmitters that are not bound do not affect the game.

**Comment by isomd** [comment]
better mc 1.20.1

**Comment by NewJumper** [comment]
provide a crash log, mod version, and platform. this bug seems as if it was fixed before (#191)
if you dont fill out the bug report properly, it makes it hard for us to actually fix a bug

**Comment by isomd** [comment]
sorry,i don't know how to do that...i just a newcomer.can i give you a screenshot?

**Comment by isomd** [comment]
maybe it's (#191),my version too old
