### ISSUE TITLE
Enchanting Warden Helmet makes it loose its horns

### ISSUE THREAD

**Issue by xheystella** [KyaniteMods/DeeperAndDarker#242]
**Minecraft Version**: 1.20.1
**Mod Version**: 1.2.0
**Mod Loader**: forge

**Description**:
When the Warden Helmet is enchanted it looses its unique horns. This has been both veryfied on solo and multiplayer, and just one enchant makes it loose the unique appearance. 

**To Reproduce**:
1. Craft a Warden Helmet.
2. Using anvil and book enchant the Warden Helmet.
3. Equip the Helmet and see the horns are missing.

**Screenshots**:
First two screenshots are of not enchanted helmet appearing correctly in the game, and the other two are the helmet enchanted simply with mending.
![nonenchant stats](https://github.com/KyaniteMods/DeeperAndDarker/assets/150959527/fd147bed-1185-4e7d-ad85-3d5a1cbd15af)
![nonenchant](https://github.com/KyaniteMods/DeeperAndDarker/assets/150959527/b2d6baa3-d28d-43d3-928b-fd3ff3216bd9)
![enchanted stats](https://github.com/KyaniteMods/DeeperAndDarker/assets/150959527/2d8fbcc1-6e63-4522-bac5-a73570bb9df3)
![enchanted](https://github.com/KyaniteMods/DeeperAndDarker/assets/150959527/94658726-0dc1-4c08-8ee4-117546368fc4)

**Additional context**:
This has been used along all the mods inh the 'Better Minecraft' modpack, and has not been tested separately.

**Comment by NewJumper** [comment]
use the latest version of the mod
