### ISSUE TITLE
No warden drop items in 1.2.3 mod version

### ISSUE THREAD

**Issue by Prasan-1** [KyaniteMods/DeeperAndDarker#243]
**Minecraft Version**: 1.19.2
**Mod Version**: 1.2.3
**Mod Loader**: fabric

**Description**:
I have killed over 100 wardens till now, I haven't gotten a single heart of the deep or warden carpace(I have looting 3) unless I go to creative mode.

**To Reproduce**:
Kill a warden, no drops other than the original game drops.

**Screenshots**:
None

**Additional context**:
No drops thats all. Not a crash.

**Comment by NewJumper** [comment]
use the latest version of the mod

**Comment by Prasan-1** [comment]
It isnt working in the latest mod as well

**Comment by Prasan-1** [comment]
> use the latest version of the mod

The warden isnt dropping the items

**Comment by Prasan-1** [comment]
I am also using other modpacks but none of them have anything to do with droprates/ancient city

**Comment by NewJumper** [comment]
you said you were using 1.1.6? which version are you using now?

**Comment by Prasan-1** [comment]
The latest one

**Comment by NewJumper** [comment]
you can't just say the latest one. provide the exact version to confirm it is the latest one

**Comment by Prasan-1** [comment]
1.2.3

**Comment by Prasan-1** [comment]
Any updates?

**Comment by Pedro270707** [comment]
It does seem to drop, maybe something else is changing the warden's loot table

**Comment by Prasan-1** [comment]
https://drive.google.com/drive/u/2/folders/19DY_ziBgTB9WoYxs3SX57EWhEJBEojAL


These are the mods im using

**Comment by Nitjsefnie** [comment]
> https://drive.google.com/drive/u/2/folders/19DY_ziBgTB9WoYxs3SX57EWhEJBEojAL
> 
> These are the mods im using

There is no deeper and darker in your "mods im using" folder

**Comment by SKYD3RIX** [comment]
> https://drive.google.com/drive/u/2/folders/19DY_ziBgTB9WoYxs3SX57EWhEJBEojAL
> 
> These are the mods im using

Your mods may not be the problem, if you are potentially using any data packs that alter the wardens loot table in anyway (i.e. vanilla tweaks - more mob heads) it'll end up blocking this mods items from being dropped

Removing such datapack or altering the datapack to remove the wardens loot table specifically from it, should inturn resolve the problem.
