### ISSUE TITLE
Soul Elytra not boosting player

### ISSUE THREAD

**Issue by IsaiahBloyer** [KyaniteMods/DeeperAndDarker#247]
**Minecraft Version**: 1.20.1
**Mod Version**: 1.2.3
**Mod Loader**: fabric

**Description**:
Soul Elytra does not boost the user periodically

**To Reproduce**:
Equip soul elytra

**Additional context**:
Not sure if it's some incompatibility within Better MC or a standalone issue within the mod

**Comment by NewJumper** [comment]
view changelog for deeper darker 1.2.0
