### ISSUE TITLE
Catalysis wiki page?

### ISSUE THREAD

**Issue by kaydenvg** [KyaniteMods/DeeperAndDarker#248]
**Description**:
Tried to check the Catalysis enchant wiki page and there is nothing there :(

**Comment by Pedro270707** [comment]
Done:
[Catalysis](https://github.com/KyaniteMods/DeeperAndDarker/wiki/Catalysis)
[Sculk Smite](https://github.com/KyaniteMods/DeeperAndDarker/wiki/Sculk-Smite)
