### ISSUE TITLE
Enchantment Descriptions are missing translations

### ISSUE THREAD

**Issue by DEAFG0AT** [KyaniteMods/DeeperAndDarker#249]
**Minecraft Version**: 1.19.2
**Mod Version**: 1.2.3
**Mod Loader**: Fabric

**Description**:
Descriptions for the Sculk Smite and Catalysis enchantments are not working. See images

**Screenshots**:
![2023-12-03_22 48 13](https://github.com/KyaniteMods/DeeperAndDarker/assets/104733108/31a72286-5602-4707-96b6-09abd069e6b9)
![2023-12-03_22 48 52](https://github.com/KyaniteMods/DeeperAndDarker/assets/104733108/7291dad9-616f-47c6-9240-d70ad94c3e94)

**Comment by Pedro270707** [comment]
Fixed in 1.2.4
