### ISSUE TITLE
Sculk Snapper Crashing Game

### ISSUE THREAD

**Issue by GrimmlinGames** [KyaniteMods/DeeperAndDarker#250]
**Minecraft Version**: 1.19.2
**Mod Version**: 1.1.6
**Mod Loader**: fabric

**Description**:
Partner and I spawned one in our survival world out of curiosity since we couldn't find any in the OtherSide, kept crashing our game every 10 seconds until he was able to kill it before he crashed. Mine is stuck in the Otherside so we're now banned from that place forever because mine ran off so I can't kill it in time. I tried to find the Mod rewrite version of the mod to download for us but I can't fine it, I'm a bit small brain.

**Comment by NewJumper** [comment]
use the latest version of the mod before reporting an issue

**Comment by GrimmlinGames** [comment]
> use the latest version of the mod before reporting an issue

I thought I was using the latest before I read about the Mod rerite but I cannot find it, which I stated above

**Comment by NewJumper** [comment]
it should be on curseforge: https://www.curseforge.com/minecraft/mc-mods/deeperdarker/files/4934388

**Comment by GrimmlinGames** [comment]
> it should be on curseforge: https://www.curseforge.com/minecraft/mc-mods/deeperdarker/files/4934388

Thank you
