### ISSUE TITLE
[Forge - 1.19.2] Enchantment descriptions missing

### ISSUE THREAD

**Issue by KneepelJC** [KyaniteMods/DeeperAndDarker#251]
**Minecraft Version**: 1.19.2
**Mod Version**: 1.2.2
**Mod Loader**: forge

**Description**:
Whenever you hover over an item with with an enchantment from the mod, it will not display the correct description and will instead show "enchantment.deeperdarker.x.desc"

**To Reproduce**:
View the description for any item with an enchantment from Deeper and Darker 

**Additional context**:
Duplicate issue of https://github.com/KyaniteMods/DeeperAndDarker/issues/249 - was fixed on fabric version 1.2.4 but remains in forge for 1.19.2

**Comment by NewJumper** [comment]
fixed in future version
