### ISSUE TITLE
[Forge 1.20.1] soul elytra not giving boost while flying

### ISSUE THREAD

**Issue by DRAKONEK** [KyaniteMods/DeeperAndDarker#252]
simply put the soul elytra doesn't give the boost while flying. And after 10 minutes of constant flying i think something is broken
to replicate just use it

**Comment by NewJumper** [comment]
doesnt boost as in automatically boost? or it doesnt work with fireworks

**Comment by DRAKONEK** [comment]
doesn't work automatically. works fine with rockets. did you discontinue it ? i checked and it is the same in fabric 1.20.2, but in mod showcases it is show to work(1.19)

**Comment by NewJumper** [comment]
yea we removed the feature because some people liked it and some didnt. we are currently developing an alternative to the automatic boost

**Comment by DRAKONEK** [comment]
oh, hope it goes well, good luck.
