### ISSUE TITLE
[Forge 1.20.1] stalker not spawning

### ISSUE THREAD

**Issue by DRAKONEK** [KyaniteMods/DeeperAndDarker#253]
Mod version 1.2.1
Description:
as stated in the title the stalker is not spawning in 1.20.1. The egg works but breaking pots doesn't ( overe 50 broken and 3 ancient temples visited and nothing

To Reproduce:
1. go to the new dimension
2. locate the ancient temple 
3. break all the vases

**Comment by NewJumper** [comment]
stalker is extremely rare

**Comment by DRAKONEK** [comment]
oh. What are the chances of it spawning if i may know ?
i broke them is survival but does breaking them in creative not work because when i tryed they didn't drop anything

**Comment by DRAKONEK** [comment]
ok after further testing yes it spawns but after destroying about 15 stacks of vases one spawned so yes it spawns but the ods are astronimcial. there are about 45 pots in a single temple so you would have to visit like 24 of them to get single to spawn. but mabey my luck is just bad

**Comment by NewJumper** [comment]
the rates have been increased in a future update
