### ISSUE TITLE
Item deletion bug for skulk transmitters

### ISSUE THREAD

**Issue by Kostaki01** [KyaniteMods/DeeperAndDarker#256]
**Minecraft Version**: 1.20.1
**Mod Version**: 1.2.1
**Mod Loader**: Forge

**Description**:
If a chest is not loaded, items can still be put in the chest using the skulk transmitter. This causes loss of items as they are not there when you go back to the chest.

**To Reproduce**:
1. Go to a new world. Teleport to 0 ~ 0.
2. Get a skulk transmitter and a double chest. Link the transmitter to the chest. Put a few items in there.
3. Teleport yourself to 1000 ~ 1000.
4. Right-click the skulk transmitter. It should show you the chest inventory. Place items in there, then exit out of the menu.
5. Teleport back to the chest at 0 ~ 0. Notice how the items you put in the chest are now missing.

**Comment by NewJumper** [comment]
I am unable to recreate this. Maybe it was fixed in dev. Could you provide a video if possible?

**Comment by NewJumper** [comment]
#233 duplicate
