### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by Redark6182** [KyaniteMods/DeeperAndDarker#257]
**Minecraft Version**: 1.19.2
**Mod Version**: 1.2.2
**Mod Loader**: forge

**Description**:
so im playing with my friend in a "survival" game with few mods we added some mods after starting it like twilight foest and no problems but today we added deeper and darker and the aether and the mod didnt load like there was no item of deeper and darker no elytra no heart of the deep not anything of that (and for the aether too) not a section in the creative mod

**To Reproduce**:
1. Go to curseforge app
2. Click on your modpacks and the add more content of your modpack you want to add
3. Select deeper and darker (without deciding the version) and do that with aether (or the other mods if you want to be same)
4. launch go to your survival game and see nothing (be in creative)

**Screenshots**:
![image](https://github.com/KyaniteMods/DeeperAndDarker/assets/155379386/f1f9090b-110b-45e6-b410-33a14c95ee12)
![image](https://github.com/KyaniteMods/DeeperAndDarker/assets/155379386/ed96c661-2f89-4f3c-aad9-ce73ad1f502a)
![image](https://github.com/KyaniteMods/DeeperAndDarker/assets/155379386/2d35fd32-4ef1-4371-8979-1826d5345517)
![image](https://github.com/KyaniteMods/DeeperAndDarker/assets/155379386/234822bf-506d-4be7-8c8c-5d9e99b292a6)
![image](https://github.com/KyaniteMods/DeeperAndDarker/assets/155379386/eede081a-e002-4583-bac7-98ff302650ca)
![image](https://github.com/KyaniteMods/DeeperAndDarker/assets/155379386/8da00687-0eac-4a45-a0eb-2ab30cb0f86f)
![image](https://github.com/KyaniteMods/DeeperAndDarker/assets/155379386/d94c1b49-04ce-4d6c-85ab-0161a9458bcf)

**Additional context**:

**Comment by NewJumper** [comment]
could you export your modpack and send a copy?
