### ISSUE TITLE
Localized Biome Name

### ISSUE THREAD

**Issue by PinkLasagna03** [KyaniteMods/DeeperAndDarker#259]
**Minecraft Version**: 1.20.1
**Mod Version**: 1.2.1
**Mod Loader**: forge

**Description**:
Due to now giving the biomes localized names, in Xearo's map mods their names show up weird formatted

**To Reproduce**:
1. Install Deeper&Darker, Xearo's minimap and world map
2. visit Deeper Darker Biomes in the Otherside
3. Look at the Biome Names

**Screenshots**:
![2024-01-09_01 20 13](https://github.com/KyaniteMods/DeeperAndDarker/assets/139581723/d64bf247-c95b-4e66-b6fb-856b08322c8d)
![2024-01-09_01 20 19](https://github.com/KyaniteMods/DeeperAndDarker/assets/139581723/5c344255-103f-419a-8fb5-aad610fa4f6a)

**Comment by NewJumper** [comment]
#223
