### ISSUE TITLE
Summon warden advancement doesn't trigger

### ISSUE THREAD

**Issue by nitrodynamite18** [KyaniteMods/DeeperAndDarker#26]
The advancement trigger used by the "summon_warden" advancement does not actually detect Warden spawns, only golem and Wither summoning. This advancement needs a custom trigger specifically for detecting Warden spawns.

**Comment by NewJumper** [comment]
Maybe an alternative could be to kill the warden to get the achievement?

**Comment by nitrodynamite18** [comment]
You know what? You're right. Changing now.

**Comment by nitrodynamite18** [comment]
You now kill the Warden for the advancement.
