### ISSUE TITLE
Ancient Temple Spawning Underground

### ISSUE THREAD

**Issue by PinkLasagna03** [KyaniteMods/DeeperAndDarker#260]
**Minecraft Version**: 1.20.1
**Mod Version**: 1.2.1
**Mod Loader**: forge

**Description**:
Upon locating the Ancient Temple, 9/10 times I find it underground

**Screenshots**:
![2024-01-10_17 46 02](https://github.com/KyaniteMods/DeeperAndDarker/assets/139581723/b6dbaeec-b0fe-471e-b024-6ef92c388d07)
![2024-01-10_17 46 07](https://github.com/KyaniteMods/DeeperAndDarker/assets/139581723/0fec6655-cf56-4945-8549-4a9904a9bbe5)
![2024-01-10_17 46 21](https://github.com/KyaniteMods/DeeperAndDarker/assets/139581723/e3b95b45-95bf-433b-8ab2-d99f6d8014d3)

**Comment by NewJumper** [comment]
this is due to the fact that the temple ALWAYS spawns on y18. We may or may not fix this
