### ISSUE TITLE
[BUG/Suggestion] Metal Ore Smelting/Blasting parity with Vanilla and other mods

### ISSUE THREAD

**Issue by Mitchell5200** [KyaniteMods/DeeperAndDarker#261]
**Minecraft Version**: 1.19.2
**Mod Version**: 1.19.2-1.2.2
**Mod Loader**: forge, 43.2.14

**Description**:
In Vanilla MC (and all other mods), metal ores smelt directly to ingots, however in DeeperDarker, the metal ores added smelt to the raw versions first, then that raw is smelted to the ingot.
I request the Datagen to be changed so that the `"result"` of the below is `"minecraft:iron_ingot"`, not `"minecraft:raw_iron"`, same for Gold and Copper, for both Sculk Stone and Gloomslate Variants
https://github.com/KyaniteMods/DeeperAndDarker/blob/5ed4e047191ff0ed33fdbec4301b5eb5fd65ed3d/src/generated/resources/data/deeperdarker/recipes/raw_iron_from_blasting_sculk_stone_iron_ore.json#L1-L10
 
**To Reproduce**:
1. Click on uses in JEI for vanilla Iron/Gold/Copper ore, 
2. Compare to Sculk Stone/Gloomslate Variants of Iron/Gold/Copper ore 

**Screenshots**:
Iron ore Blasting recipes shown below (with Almost Unified Off)
![2024-01-15_20 11 27](https://github.com/KyaniteMods/DeeperAndDarker/assets/45913837/75c42793-0271-418b-85b0-b6acff1cc4f7)
![2024-01-15_20 10 16](https://github.com/KyaniteMods/DeeperAndDarker/assets/45913837/66794ad1-fd03-4fe6-b282-a6817f77690d)

**Additional context**:
Initially discovered in ATM8, additionally tested without Almost Unified running for Ores, confirmed in an isolated instance with just JEI and Deeperdarker, and a Github Code source exploration

**Comment by NewJumper** [comment]
have no idea how this hasn't been noticed till now!

**Comment by cranberriez** [comment]
This still appears to be a bug in the newest 1.20.1 version of the mod.

**Comment by NewJumper** [comment]
it will be fixed in the next update
