### ISSUE TITLE
Transmitter Crashing Game

### ISSUE THREAD

**Issue by GreenYTFR123** [KyaniteMods/DeeperAndDarker#262]
**Minecraft Version**: 1.20.2
**Mod Version**: most recent
**Mod Loader**: fabric

**Description**:
there's a glitch where if you have a transmitter linked to something and go to another dimension it unlinks it which is normal but if you
right click while holding it or hovering over it using your inventory it crashes the game

**Comment by Pedro270707** [comment]
It doesn't happen in the latest version, so either I can't reproduce it or your "most recent" version isn't the most recent version

**Comment by BetoBox** [comment]
In the 1.2.1 of the Forge Version this still happening, I have the exact same problem

**Comment by saltacc** [comment]
Same here, 1.2.1 forge version. Can't do anything without crashing, trying to remove it via NBT editing currently

Edit: seems like `/clear <username> deeperdarker:sculk_transmitter` is the easiest way to removed glitch crashing transmitters

**Comment by egriff38** [comment]
Same issue, 1.2.1 Forge
