### ISSUE TITLE
Game fails to launch

### ISSUE THREAD

**Issue by GourmetTinCan** [KyaniteMods/DeeperAndDarker#265]
**Minecraft Version**: 1.20.1
**Mod Version**: 1.2.5
**Mod Loader**: Fabric 0.15.6

**Description**:
The game fails to launch

**To Reproduce**:
1. Install mod (with other mods installed)
2. Launch game
3. It does not :(

**Crash-log/Error**:
https://pastebin.com/swd71rb6

**Additional context**:
Sorry for the rather lackluster reproduction steps, but that's basically all that happens. Removing the mod lets the game launch fine, and adding it prints out the same fabric error every time. I've tried removing a few bad apples that have caused me problems with other mods before (C2ME, Nvidium, Carpet & Extensions/Add-ons) but no dice. Also, removing every mod except Deeper & Darker (and it's dependencies) launches the game perfectly fine as intended.

Edit: Here's a drive link for all of the mods I have installed to replicate the crash, if you need them: https://drive.google.com/file/d/1vwuTb9avd65mpZbHLB3HMg4KQKDWs6US/view?usp=sharing

**Comment by Pedro270707** [comment]
It's likely a [Custom Portal API](https://github.com/kyrptonaught/customportalapi) issue, if it is maybe it was already fixed
