### ISSUE TITLE
Any files that are in curseforge dosen't work on 1.19

### ISSUE THREAD

**Issue by Wujo01** [KyaniteMods/DeeperAndDarker#268]
**Minecraft Version**: 1.19
**Mod Loader**: forge

**Description**:
Every file that I downlad dosen't work on 1.19, which is strange beacuse they say this version i supported

**To Reproduce**:
1. Go to files
2. Click on any file that says 1.19
3. Try turn on 
4. Mod need javafml:43 (1.19.3) have found javafml:41 (1.19)

**Comment by NewJumper** [comment]
send mod list

**Comment by Wujo01** [comment]
https://www.curseforge.com/minecraft/mc-mods/deeperdarker/files/all?page=1&pageSize=20

I have try every file that is for 1.19 Forge (version that they say its supported) and they all don't work

**Comment by NewJumper** [comment]
no, send me the list of mods in your folder

**Comment by Wujo01** [comment]
[1.19]-Epic-Knights-Armor-and-Weapons-6.3v
alwaysawitherskull_1.19.0-1.7
armorplus-1.19.2-19.1.0-beta
bygonenether-1.2.1-1.19
Castle-Dungeons-Mod-Forge-1.19
collective-1.19.0-4.30
curios-forge-1.19.2-5.1.4.2
DungeonsArise-1.19-2.1.51-beta
ExplorersCompass-1.19-1.2.4-forge
FallingTree-1.19-3.7.4
geckolib-forge-1.19-3.1.28
infinitetrading_1.19.0-2.3
jei-1.19-forge-11.1.1.239
merenc-forge-1.20.x-v3.2
MoogsCopperBeacons-1.19
OptiFine_1.19_HD_U_H9
sophisticatedbackpacks-1.19-3.18.8.655
sophisticatedcore-1.19-0.4.10.87
thedragonlib-1.19-1.0.0
torohealth-1.19-forge-2

**Comment by Wujo01** [comment]
![Zrzut ekranu (535)1](https://github.com/KyaniteMods/DeeperAndDarker/assets/158854831/20101e7d-0350-4704-8ee3-7c721ff40ca1)

**Comment by NewJumper** [comment]
you don't even have deeper darker installed
