### ISSUE TITLE
Game crash on startup with the latest version of the mod

### ISSUE THREAD

**Issue by Risto90** [KyaniteMods/DeeperAndDarker#269]
**Minecraft Version**: 1.20.1
**Mod Version**: 1.2.6
**Mod Loader**: Quilt

**Description**:
The latest version of the mod crashes Minecraft, although version 1.2.3 works correctly.

Crashlog: https://pastebin.com/rhznGPux

If you remove the Small Ships mod, the crash log changes to this: https://pastebin.com/qQ0DpbAx

At the same time, Small Ships without Deeper and Darker or with version Deeper and Darker 1.2.3 works correctly.

**Comment by Pedro270707** [comment]
I believe this is because the latest version of YACL is different from a few versions back
I've been wanting to switch to owo-lib for a while now but don't know if it's a good idea

**Comment by Pedro270707** [comment]
Fixed by switching to owo-lib
