### ISSUE TITLE
[Suggestion] Tag sculk gleam blocks as leaves so they will drop along with leaf decay when trees are chopped down

### ISSUE THREAD

**Issue by krumble1** [KyaniteMods/DeeperAndDarker#270]
**Description**:

Could you tag sculk gleam blocks as leaves, so they'll drop along with leaf decay when trees are chopped down?

I want to farm these trees so I can use the sculk gleam blocks as lights around my base, but right now they're a lot of work to deal with since you have to manually break each block, and some of them are out of reach from the ground.

**Comment by NewJumper** [comment]
this is an intended feature with no plans to change it
