### ISSUE TITLE
Cant find config folder

### ISSUE THREAD

**Issue by ondekikeci** [KyaniteMods/DeeperAndDarker#271]
I cant see deeper and darker config folder.
I want to reduce some mobs spawning. when ı go to the other side so much shattered spawn and make so much lag I just use /kill repeatedly

**Comment by NewJumper** [comment]
there is no config file for forge yet

**Comment by NewJumper** [comment]
unless you are talking about fabric

**Comment by ondekikeci** [comment]
oh ok thx
