### ISSUE TITLE
Deeper darker crashes server starup

### ISSUE THREAD

**Issue by Huntter99** [KyaniteMods/DeeperAndDarker#272]
**Minecraft Version**: 1.20.1
**Mod Version**: x.x.x
**Mod Loader**: forge 47.2.20

**Description**:
I am having a crash error while trying to use deeper darker on my server. I'm getting ```"Attempted to load class net/minecraft/client/Minecraft", @Mixin target net.minecraft.client.renderer.entity.PhantomRenderer was not found mixins.deeperdarker.json:PhantomRendererMixin```

**To Reproduce**:
1. Add deeper darker
2. Load server startup
3. Server crash with error

**Comment by NewJumper** [comment]
what mod version are you using

**Comment by Huntter99** [comment]
1.2.1.jar

**Comment by NewJumper** [comment]
unable to recreate. does this happen on server startup or when you go to the otherside dimension?

**Comment by Huntter99** [comment]
I apologize i meant to re-comment yesterday, its an issue with my server
it's not deeper darker directly. I apologize if i wasted your time. I asked
support on my server and got someone in training who miss led me.

**Comment by ZizzyZizzy** [comment]
@Huntter99 Having the exact same issue. What did they do to resolve yours?

`[11Feb2024 10:37:51.588] [main/WARN] [mixin/]: Error loading class: net/minecraft/client/renderer/entity/PhantomRenderer (java.lang.ClassNotFoundException: net.minecraft.client.renderer.entity
.PhantomRenderer)
[11Feb2024 10:37:51.588] [main/WARN] [mixin/]: @Mixin target net.minecraft.client.renderer.entity.PhantomRenderer was not found mixins.deeperdarker.json:PhantomRendererMixin from mod deeperdar
ker
`
This is on a dedicated server, so I don't know why it would be trying to load a client mod.

@NewJumper Does Deeper Darker need to be on the server and the client? The description says it adds new features and a new dimension, which seems to indicate it must be on the server as well.

**Comment by Huntter99** [comment]
If its not causing a crash i wouldn't worry about it my issue is related to
my server over clocking my ram for no reason. I uploaded a world that could
run off 2gb to my 8gb ram server and its still crashing from "ram"
according to my server support even after a full reset and fresh world. Not
sure what my issue is yet, if it pertains to deeper darker in anyway I'll
update my post.

**Comment by ZizzyZizzy** [comment]
@Huntter99 Thanks.

Regarding your issue, Minecraft uses a shitton of memory, and every world (including extra dimensions) use memory to hold the spawn area too. I can tell you from 10 years of hosting Minecraft dedicated servers, 2GB is barely enough to run any modded server these days.

**Comment by NewJumper** [comment]
> Does Deeper Darker need to be on the server and the client? The description says it adds new features and a new dimension, which seems to indicate it must be on the server as well.

Deeper Darker does need to be on both server and client side

**Comment by Huntter99** [comment]
Thats what I'm saying though is my world works off 2gb in single player yet
wont run on my 8gb server with no player even on?

**Comment by NewJumper** [comment]
might be a server issue. have not been able to recreate

**Comment by NewJumper** [comment]
can you recreate this crash again? but only with Deeper Darker installed?
