### ISSUE TITLE
Sculk Transmitter crashes the game 

### ISSUE THREAD

**Issue by Cornicaphobia** [KyaniteMods/DeeperAndDarker#281]
**Minecraft Version**: 1.20.1
**Mod Version**: 1.20.1-1.2.1 (10/20/23)
**Mod Loader**: Forge

**Description**:

After the bug occurred, hovering over the sculk transmitter in my inventory & using it in any way crashes the game. 

**To Reproduce**:

I don't know how to reproduce it.
It happened randomly with the first transmitter, the second transmitter got bugged after I entered then exited the nether.

It could have possibly been from being launched by a weighted ejector from the Create mod, because it only happened after I did that, worked totally fine before.

**Screenshots**:

![image_2024-02-25_163433284](https://github.com/KyaniteMods/DeeperAndDarker/assets/90018948/a54732d1-50cd-4708-b76b-4a6ff9c3dd49)

**Additional context**:

Both linked chests are in the overworld, and they were in rendered chunks when I tried to use the linked transmitters on them.

Advanced tooltips are enabled

Playing on a modded server, not a local world

Using a modpack, not _just_ Deeper and Darker

Crash log: 

[crash-2024-02-25_16.31.57-client.txt](https://github.com/KyaniteMods/DeeperAndDarker/files/14398419/crash-2024-02-25_16.31.57-client.txt)

**Comment by Cornicaphobia** [comment]
> The server may not be using enough RAM. I also use a modpack and my server uses 32GB RAM. You can set the RAM to use in your start.bat file

I have 6 GB allocated on my end, I'm not sure how much RAM is given to the server but it runs pretty well so I wouldn't assume it has too little

Even then, for the game to crash by hovering over an item (the server doesn't crash, I do) I don't think it's really a memory issue, more an issue of the item being broken because of some bug

**Comment by Linguardium** [comment]
https://github.com/KyaniteMods/DeeperAndDarker/blob/12fb53d9b96338400b3e08c7cb174e63b4192eaf/src/main/java/com/kyanite/deeperdarker/content/items/SculkTransmitterItem.java#L63-L67

The mod assumes that having NBT means the transmitter has a block position saved, but nbt can be added for a bunch of different reasons without initializing that. Seems to be a missing `contains` check for the blockpos

**Comment by SilentChapter** [comment]
Ah okey.

Linguardium ***@***.***> schrieb am Di., 27. Feb. 2024, 13:10:

**Comment by XAgent1990** [comment]
@Linguardium is correct this is a general bug with the sculk transmitter.
I fixed this https://github.com/KyaniteMods/DeeperAndDarker/pull/280 for the version 1.19.2. (merged by now)

**Comment by Linguardium** [comment]
> @Linguardium is correct this is a general bug with the sculk transmitter. I fixed this #280 for the version 1.19.2. (merged by now)

@XAgent1990 There are still quite a few places that the game will crash in fabric-1.19.2's SculkTransmitter item code for the same reason (unchecked nbt reading). Do you want an issue for each or is this issue still being looked at?

**Comment by XAgent1990** [comment]
> > @Linguardium is correct this is a general bug with the sculk transmitter. I fixed this #280 for the version 1.19.2. (merged by now)
> 
> @XAgent1990 There are still quite a few places that the game will crash in fabric-1.19.2's SculkTransmitter item code for the same reason (unchecked nbt reading). Do you want an issue for each or is this issue still being looked at?

it has not been updated yet, meaning my fixed code isn't used yet in any published version
If you want 1.19.2 in a fixed version, use mine for the time being
https://legacy.curseforge.com/minecraft/mc-mods/deeper-and-darker-deathunity

**Comment by Linguardium** [comment]
I was specifically talking about this repo's current codebase

**Comment by XAgent1990** [comment]
@Linguardium you can make  an issue for them if you actually still find some
https://github.com/XAgent1990/DeeperAndDarker

**Comment by XAgent1990** [comment]
https://github.com/XAgent1990/DeeperAndDarker/blob/fabric-1.19.2/src/main/java/com/kyanite/deeperdarker/content/items/SculkTransmitterItem.java
I don't see any code where I access the tags without specifically checking them beforehand

**Comment by XAgent1990** [comment]
https://github.com/KyaniteMods/DeeperAndDarker/blob/fabric-1.19.2/src/main/java/com/kyanite/deeperdarker/content/items/SculkTransmitterItem.java
All my code is also already in the official repo
