### ISSUE TITLE
Visual glitch

### ISSUE THREAD

**Issue by viktordimov** [KyaniteMods/DeeperAndDarker#283]
**Minecraft Version**: 1.20.4
**Mod Version**: 1.2.6
**Mod Loader**: Fabric 1.20.4

**Description**:
Shriek worm texture gets glitched after a few seconds. The worm is still targetable and it seems like you're hitting the air

**To Reproduce**:
1. Go to a creative world
2. Grab a Shriek Worm spawn egg
3. Wait a few secconds
4. See glitch

**Screenshots**:

![2024-02-28_14 48 19](https://github.com/KyaniteMods/DeeperAndDarker/assets/51263553/f7f0e25f-20e8-4976-9422-b73e412a0941)

![2024-02-28_14 48 42](https://github.com/KyaniteMods/DeeperAndDarker/assets/51263553/3bfc3adb-6055-4689-9ce6-26874dc07369)

![2024-02-28_14 52 04](https://github.com/KyaniteMods/DeeperAndDarker/assets/51263553/bfa9b82e-3527-4d18-aaf3-8b042dbad1e5)

**Comment by Pedro270707** [comment]
oops, I forgot Forge didn't fix that yet
