### ISSUE TITLE
Soul elytra doesn't boost

### ISSUE THREAD

**Issue by MaeLecT** [KyaniteMods/DeeperAndDarker#284]
**Minecraft Version**: 1.20.1
**Mod Version**: 1.1.2
**Mod Loader**: forge

**Description**:
The soul elytra is now just a regular elytra with 3 armor points ???, like it's suck we need the boost 

**To Reproduce**:
equip the soul elytra and nothing happens

**Additional context**:
there is also not the particle with the elytra even if I enabled them

**Comment by Pedro270707** [comment]
Not a bug, that version doesn't have the boost due to it having bad controls. It will be added back in the next Forge version though with better control over the boost.
