### ISSUE TITLE
Wiki is all "WIP".  What does this do?

### ISSUE THREAD

**Issue by allanonmage** [KyaniteMods/DeeperAndDarker#285]
**Minecraft Version**: 1.xx.x
**Mod Version**: x.x.x
**Mod Loader**: forge/fabric

**Description**:
If you're going to refer people to the wiki instead of having a description on Curseforge, you should have more stuff in it.  Over 90% of the things I clicked on in the Wiki were "WIP" or gave me a permission error.

**To Reproduce**:
2. Click on '...'
3. Scroll down to '...'

**Screenshots**:

**Additional context**:
Add any other context about the problem here: crash reports, logs, and any other details.

**Comment by NewJumper** [comment]
We'll make it public once we have finished working on it
