### ISSUE TITLE
[Worker-ResourceReload-6/WARN] 1.20.1 Forge

### ISSUE THREAD

**Issue by Krimatoria** [KyaniteMods/DeeperAndDarker#286]
**Minecraft Version**: 1.20.1 
**Mod Version**: Deeperdarker-forge-1.20.1-1.2.1.jar
**Mod Loader**: Forge 47.2.7

**Description**:
I don't know visually, I haven't gone down into the depths yet, I'm just tracking errors

**To Reproduce**:

- deeperdarker-forge-1.20.1-1.2.1.jar
- Deep Dark Regrowth 1.2.4.4 - 1.20.1.jar
- sculkhorde-1.20.1-0.8.9.jar

**Screenshots**:

**Additional context**:
> [00:55:42] [Worker-ResourceReload-6/WARN] [minecraft/ModelBakery]: Unable to load model: 'deeperdarker:sculk_tendrils_plant#inventory' referenced from: deeperdarker:sculk_tendrils_plant#inventory: java.io.FileNotFoundException: deeperdarker:models/item/sculk_tendrils_plant.json
> [00:55:42] [Worker-ResourceReload-6/WARN] [minecraft/ModelBakery]: Unable to load model: 'deeperdarker:sculk_vines_plant#inventory' referenced from: deeperdarker:sculk_vines_plant#inventory: java.io.FileNotFoundException: deeperdarker:models/item/sculk_vines_plant.json
> [00:55:42] [Worker-ResourceReload-6/WARN] [minecraft/ModelBakery]: Unable to load model: 'deeperdarker:otherside_portal#inventory' referenced from: deeperdarker:otherside_portal#inventory: java.io.FileNotFoundException: deeperdarker:models/item/otherside_portal.json
>

**Comment by NewJumper** [comment]
you can ignore these errors
