### ISSUE TITLE
Duplication glitch using Sculk Transmitter.

### ISSUE THREAD

**Issue by CakeRulez** [KyaniteMods/DeeperAndDarker#292]
**Minecraft Version**: 1.20.1
**Mod Version**: 1.2.1
**Mod Loader**: forge

**Description**:
Duplication glitch using Sculk Transmitter.

**To Reproduce**:
Fill a double chest with Shulker Boxes
Link to Sculk Transmitter
Go far away to deload the area
Use Sculk Transmitter and take a Shulker Box
Close the Sculk Transmitter
Use the Sculk Transmitter and there should be the Shulker Box you just took still in the chest

**Screenshots**:

![2024-03-17_09 20 22](https://github.com/KyaniteMods/DeeperAndDarker/assets/163722501/d0ae24ee-3aa2-4fa4-91a7-c8b6995c43bd)
Full Chest of boxes

![2024-03-17_09 20 31](https://github.com/KyaniteMods/DeeperAndDarker/assets/163722501/7d7b8d71-399d-4d2d-88dc-536e43f7bfa2)
Linking the Sculk Transmitter

![2024-03-17_09 21 05](https://github.com/KyaniteMods/DeeperAndDarker/assets/163722501/27952798-7057-4767-9850-e3d77334cf11)
Opening the Sculk Transmitter from very far away (~5k blocks), and taking a box out

![2024-03-17_09 21 11](https://github.com/KyaniteMods/DeeperAndDarker/assets/163722501/cf5ae68a-ada9-4fae-8bab-abc7da3b7195)
Box reappearing in linked chest

![2024-03-17_09 21 14](https://github.com/KyaniteMods/DeeperAndDarker/assets/163722501/10a8a72a-56b3-4c11-bfa1-93f92c136a2a)
Showing all boxes still being there

**Additional context**:
Can be infinitely repeated
Even when going back to the chest the boxes that were duped still exist along with the original box

**Comment by Eminence5070** [comment]
Can confirm for fabric 1.19.2. Works with any item (I used diamonds).

**Comment by NewJumper** [comment]
fixed for forge in 6cd94ed84b848a83f243f98fb6deb037abc7ad0a

**Comment by Pedro270707** [comment]
Fixed for Fabric https://github.com/KyaniteMods/DeeperAndDarker/commit/184004a7e0459975a57cd2aea2b171e39ce22351
