### ISSUE TITLE
Portal in the Other Side temple not functioning

### ISSUE THREAD

**Issue by Fern298** [KyaniteMods/DeeperAndDarker#299]
**Minecraft Version**: 1.20.1
**Mod Version**: 1.2.6
**Mod Loader**: fabric

**Description**:
Me and a friend found a temple in the other side but couldn't get the portal to work. we cleared the sculk, fixed the frame, removed the excess blocks, tried other block configurations, but we couldnt get it to light no matter what we tried. How do you do it and what are we doing wrong?

Also, this temple only had two floors: the top one with the well and another with the receiver chest. No flooded room. Is that normal?
I tried leaving a comment on the Curse page but it wouldn't let me.

**To Reproduce**:
It just isn't working. I dont know how to replicate it beyond that.

**Screenshots**:

**Additional context**:
Add any other context about the problem here: crash reports, logs, and any other details.

**Comment by Darking151** [comment]
hey, i have also the same issue. I use aternos to play with my friends. but can't open the portal

**Comment by Littlebluejay45** [comment]
I found how to fix it you have to configure it so the minimum portal width and height to be 3 for height and 6 for width.

*Edit* You can config it with something like a mod menu.

**Comment by Pedro270707** [comment]
Fixed in 1.3.2, the fix was just changing the default settings https://github.com/KyaniteMods/DeeperAndDarker/commit/c5347295bd458461d793b6a86ba53c0df8ad24b2
