### ISSUE TITLE
minecraft version 1.20

### ISSUE THREAD

**Issue by Salamingos** [KyaniteMods/DeeperAndDarker#301]
**Minecraft Version**: 1.20
**Mod Version**: 1.2.5
**Mod Loader**: fabric

**Description**:
I just drop the mod into my sevrer and its broke my worlds in server and now 
when I try to upload my worlds into another server my worlds just crushing new server

map download 
[race.zip](https://github.com/KyaniteMods/DeeperAndDarker/files/15189619/race.zip)

**Comment by NewJumper** [comment]
dont send the map, send the crash report

**Comment by Salamingos** [comment]
https://mclo.gs/5SCewEO here it is

**Comment by Pedro270707** [comment]
That is not Deeper and Darker, it seems to be a mod or data pack called Deeper Dark
