### ISSUE TITLE
[Forge 1.20.1] Echo logs are missing standard tags

### ISSUE THREAD

**Issue by vizthex123** [KyaniteMods/DeeperAndDarker#302]
They don't have the `minecraft:logs` tag, but Echo Planks have the `minecraft:planks` tag.

**Comment by NewJumper** [comment]
the do. they have the `logs_that_burn` tag, which is used by the `logs` tag

**Comment by vizthex123** [comment]
> the do. they have the `logs_that_burn` tag, which is used by the `logs` tag

I just checked, and all but the regular Echo Log are missing item tags.

Running v1.2.1 of the mod on Forge 1.20.1.
![image](https://github.com/KyaniteMods/DeeperAndDarker/assets/31721920/f462c5be-a31a-488d-a9d6-b32b25c69e52)

![image](https://github.com/KyaniteMods/DeeperAndDarker/assets/31721920/5b19176a-d34f-4e38-87d5-c0528106892c)

![image](https://github.com/KyaniteMods/DeeperAndDarker/assets/31721920/d9c35466-b772-49ba-93b0-556be09d70be)

![image](https://github.com/KyaniteMods/DeeperAndDarker/assets/31721920/3a9ca19d-f397-43fc-b063-52e1da4538d9)

**Comment by NewJumper** [comment]
its all handled by the `echo_logs` tag

**Comment by NewJumper** [comment]
is there actually an issue with the logs not burning? cause if there isn't, the tags work as intended

**Comment by vizthex123** [comment]
> is there actually an issue with the logs not burning? cause if there isn't, the tags work as intended

Nope, all except the regular one do not have a burn time. The main issue when I reported this is that they can't be used in any recipe that uses the `minecraft:logs` tag.
