### ISSUE TITLE
[BUG] Broken Crafting Shaped Recipe

### ISSUE THREAD

**Issue by KakashoLin** [KyaniteMods/DeeperAndDarker#308]
**Minecraft Version**: 1.20.1
**Mod Version**: 1.2.1 10/20/2023
**Mod Loader**: forge

**Description**:
[13:45:55] [WARN] Failed to parse recipe 'deep_aether:stratus_smithing_template_from_gravitite[minecraft:crafting_shaped]'! Falling back to vanilla: ItemStack 'result' can't be empty!

**To Reproduce**:
Start the game and have it load the recipe then had a program to show you invalid or broken recipes.

**Screenshots**:
NA

**Additional context**:
Might be a fabric recipe that is loading on forge, but that's because the last couple reports I filled out were other mods loading fabric files when they weren't suppose to.

**Comment by NewJumper** [comment]
this is not a deeper darker issue
