### ISSUE TITLE
Sculk Shrieker not spawning warden nor giving the dark effect when triggered in temple

### ISSUE THREAD

**Issue by Anonyku05** [KyaniteMods/DeeperAndDarker#309]
**Minecraft Version**: 1.20.4
**Mod Version**: 1.2.6
**Mod Loader**: fabric

**Description**:
Basically in the title, when in a temple and the Sculk Shrieker is triggered, nor it's giving the dark effect, nor a warden is spawning, it's like they were placed in creative mode (i say that cuz in creative when placing a sculk shrieker and triggering it afterwards it won't have vany effect besides the screams

**To Reproduce**:
1. Go to a temple
2. Trigger Sculk Shrieker

**Screenshots**:

https://github.com/KyaniteMods/DeeperAndDarker/assets/48128391/32fc702a-b6ac-45cc-b850-0a24c40bedfa

**Additional context**:
None

**Comment by Littlebluejay45** [comment]
The reason its not spawning the warden is because you have 3 strikes then it will spawn and you only triggered it once

**Comment by Anonyku05** [comment]
Late response but, we don't see it in the record but i triggered it more than 3 times and still nothing, not even the dark effect

**Comment by Pedro270707** [comment]
Fixed in 1.3.2

**Comment by Anonyku05** [comment]
Is the 1.3.2 is yet to be released ? And will it be available on 1.20.4 ?

**Comment by Pedro270707** [comment]
Yes to both questions
