### ISSUE TITLE
Sculk Snapper [Nerf Or Config Request]

### ISSUE THREAD

**Issue by Fyoncle** [KyaniteMods/DeeperAndDarker#310]
**Description**:
I would wish nerf snapper was nerfed, ATLEAST A CONFIG ADDED TO reduce drop chance of the books it gives us after tamed, its so easily to be abused by taming 30 of them and making a infinite book farm.

**Additional context**:
Add any other context about the feature here.

**Comment by Fyoncle** [comment]
No config...? i want a config to limit the sculk snappers can be tamed per player :(

Example : 1 sculk snapper max can be tamed per player.

**Comment by NewJumper** [comment]
dont really want to limit how many snappers a player can tame, but a config to limit how many books per snapper will be added

**Comment by Fyoncle** [comment]
> dont really want to limit how many snappers a player can tame, but a config to limit how many books per snapper will be added

Will this update also be backported for 1.20.1 Fabric? i am playing on 1.20.1 Fabric and this op thingy is getting abused by every player
