### ISSUE TITLE
Weird Texts On Console

### ISSUE THREAD

**Issue by Fyoncle** [KyaniteMods/DeeperAndDarker#313]
**Minecraft Version**: 1.20.1
**Mod Version**: 1.2.6
**Mod Loader**: Fabric

**Description**:
Its just in the console.

**To Reproduce**:
1. Open the game
2. Enter a world
3. You'll see the error in the console even tho you dont use anything related to deeper and darker mod

**Screenshots**:
No need

**Additional context**:
https://mclo.gs/61JtmVe

**Comment by NewJumper** [comment]
its a naming problem in a tag @Pedro270707

**Comment by NewJumper** [comment]
the other errors are from other mods

**Comment by Fyoncle** [comment]
Oh cool, will it be fixed?

**Comment by Pedro270707** [comment]
It was already fixed in a [future update](https://github.com/KyaniteMods/DeeperAndDarker/commit/7667ff384b05214e6a9be965078c844759ac7bf2)
