### ISSUE TITLE
Soul Elytra not letting me fly like it used to.

### ISSUE THREAD

**Issue by NightlyJade** [KyaniteMods/DeeperAndDarker#315]
**Minecraft Version**: 1.xx.x
**Mod Version**: x.x.x
**Mod Loader**: forge/fabric

**Description**: I played Limitless 6 before and I was able to fly with the Soul Elytra but they updated it and now I cant and I loved the Soul Elytra. I can barely fly anywhere with it now.
Explanation of what the bug is and how it affects the game.

**To Reproduce**:
2. Click on '...'
3. Scroll down to '...'

**Screenshots**:

**Additional context**:
Add any other context about the problem here: crash reports, logs, and any other details.

**Comment by NewJumper** [comment]
update your comment to include what version of minecraft and the mod including the modloader you are using.
