### ISSUE TITLE
1.20.1 Console TP Error

### ISSUE THREAD

**Issue by Krimatoria** [KyaniteMods/DeeperAndDarker#321]
I don't know if this is a mistake, but I can't teleport to the location through the console. It just doesn't exist, even though it's a new world.
![image](https://github.com/user-attachments/assets/8d9836d4-51b0-4e31-afd6-284b2faeace2)

**Comment by NewJumper** [comment]
1. send us english logs
2. fill out the template properly: what mod loader and mod version are you using
3. are you in the Otherside dimension
