### ISSUE TITLE
Couldn't load tag frozenlib:dont_emit_use_game_events as it is missing following references

### ISSUE THREAD

**Issue by YOUNIN15** [KyaniteMods/DeeperAndDarker#323]
**Minecraft Version**: 1.20.1
**Mod Version**: 1.2.6 (Fabric 1.20 & 1.20.1, 1.2.6)
**Mod Loader**: fabric 0.15.11, also tested with 0.16.0

**Description**:
When the server is started, the following error appears in the registry, referring to the mod

**To Reproduce**:
1. Server startup.
2. The server is started.
3. Error in registration.

**Screenshots**:
![image](https://github.com/user-attachments/assets/452b443b-2f15-42fe-bfb7-c0755da17adb)

**Additional context**:

log:
https://mclo.gs/n3dGgM3
https://api.mclo.gs/1/raw/n3dGgM3

Note: Omit the other bugs, I am notifying each mod developer.

**Comment by NewJumper** [comment]
im not the fabric dev, but it probably is fixed in a future update

@Pedro270707

**Comment by Pedro270707** [comment]
Yeah, it appears to have been fixed in 1.3.0

**Comment by YOUNIN15** [comment]
> Yeah, it appears to have been fixed in 1.3.0

When is 1.3 released?
