### ISSUE TITLE
Sculk Transmitter allows for easy item duplication

### ISSUE THREAD

**Issue by iTriedGit** [KyaniteMods/DeeperAndDarker#325]
**Minecraft Version**: 1.20.1
**Mod Version**: 1.2.1
**Mod Loader**:  Forge

**Description**:
Sculk Transmitter allows for easy item duplication. Items don't get removed from the chest,

**To Reproduce**:
1. Use the sculk transmitter to open an unloaded chest
2. Take anything out
3. Close it
4. Open it again to reveal that items are still there

**Comment by NewJumper** [comment]
duplicate of #292
