### ISSUE TITLE
Crash Upon Logging into Server, with Error "The game crashed whilst rendering entity in world Error: java.lang.NullPointerException: Registry Object not present: deeperdarker:soul_elytra"

### ISSUE THREAD

**Issue by BugReporterGuy** [KyaniteMods/DeeperAndDarker#327]
**Minecraft Version**: 1.20.1
**Mod Version**: 1.2.1
**Mod Loader**: forge

**Description**:
Crash Upon Logging into Server, with Error "The game crashed whilst rendering entity in world
Error: java.lang.NullPointerException: Registry Object not present: deeperdarker:soul_elytra" Exit Code: -1

Crash Persists after removing Modern Fix. 

**To Reproduce**:

idk, but it is consistent. 

**Screenshots**:

**Additional context**:
Add any other context about the problem here: crash reports, logs, and any other details.
[crash-2024-08-08_15.07.58-client.txt](https://github.com/user-attachments/files/16548580/crash-2024-08-08_15.07.58-client.txt)
[crash-2024-08-08_15.13.34-client.txt](https://github.com/user-attachments/files/16548583/crash-2024-08-08_15.13.34-client.txt)

**Comment by BugReporterGuy** [comment]
Issue Resolved. Caused by Serverside Mod being severely out of date.

**Comment by aaron01-dev** [comment]
may I ask what this serverside mod be?

**Comment by BugReporterGuy** [comment]
The Server had DnD on ver. 1.2.0, users who experienced the crash were on 1.2.1. The Crash only occurred if the player joining the server would chunk load an Armor Stand with their pre-login load. Loading a Chunk with an Armor Stand in it worked fine, but logging out near one caused that user to be unable to rejoin unless all Armorstands in the area were removed. 

Can't think if why this would be, tbh.
