### ISSUE TITLE
Getting teleported to any teleporting endermen or thrown ender pearls when wielding Warden sword.

### ISSUE THREAD

**Issue by AgileScarab** [KyaniteMods/DeeperAndDarker#328]
**Minecraft Version**: 1.20.1
**Mod Version**: 1.2.1
**Mod Loader**: forge

**Description**:
While wielding a Warden sword when another player throws an ender pearl or an enderman teleports the player gets teleported as well. The player wielding the Warden sword also gets the nausea status effect.

**To Reproduce**:
1. Equip Warden sword
2. Have an enderman teleport/have a friend teleport with an ender pearl

**Video showcasing the bug**:
https://streamable.com/xx9feh

**Comment by NewJumper** [comment]
This isnt even a feature for the warden sword and there is no way this could happen. There must be another mod doing this. Can you try recreating this bug with just Deeper and Darker?

**Comment by AgileScarab** [comment]
I tested this with just Deeper and Darker and it didn't happen. It seems to be an issue with either tetra or Tetranomicon as tetra has similar behaviour when a sword's handle is made out of an end rod.

**Comment by NewJumper** [comment]
Yea, i'd open an issue with those mods
