### ISSUE TITLE
Please, just allow catalysis to be disabled on servers.

### ISSUE THREAD

**Issue by AfkUserMC** [KyaniteMods/DeeperAndDarker#329]
Gamerule? Cool! Config file? Even better! Permission node? SURE!
Just- PLEASE add a way for it to be disabled. I host a server using a 1.20.1 pack which includes the Deeper And Darker mod, and every day I get complaints about the Catalysis enchantment. It can even spread sculk in OTHER PLAYERS' CLAIMS!!! I've looked everywhere and could not find a way to disable the enchant, so please, add a way to disable it.

**Comment by Daedric-Arbiter** [comment]
Why are you letting the players even have the enchantment in the first place? Disabling the enchantment would render the purpose of the enchantment entirely obsolete and therefore a waste of an enchantment item.
In my opinion, I think it is better to just have it removed from the server altogether so no player can get their hands on it.

**Comment by AfkUserMC** [comment]
> Why are you letting the players even have the enchantment in the first place? Disabling the enchantment would render the purpose of the enchantment entirely obsolete and therefore a waste of an enchantment item. In my opinion, I think it is better to just have it removed from the server altogether so no player can get their hands on it.

and how exactly would I go about doing that

**Comment by Daedric-Arbiter** [comment]
Datapacks should allow you to do so via removing them from the loot tables of chests, and the enchantment from enchanting tables.

**Comment by NewJumper** [comment]
this is a key feature of the mod that we dont plan on disabling.
