### ISSUE TITLE
Severe Performance Issues

### ISSUE THREAD

**Issue by Creativious** [KyaniteMods/DeeperAndDarker#331]
**Minecraft Version**: 1.20.1
**Mod Version**: 1.2.1
**Mod Loader**: forge

**Description**:
Not really a bug but performance issues

**To Reproduce**:
1. With my current modpack, with deeper dark the server gets 10-14 tps
2. When it's removed the server is back at 20 tps.

**Additional context**:
I'll provide the Datapack dump zip that you get when you do /perf [2024-08-13_23_40_24-world-1_20_1.zip](https://github.com/user-attachments/files/16607466/2024-08-13_23_40_24-world-1_20_1.zip)
Which is what showed that this mod was the issue.

Anyways I'll provide the mrpack file (for modrinth) for when I 
had deeper dark in the pack

[Moogic 1.2.0.zip](https://github.com/user-attachments/files/16607469/Moogic.1.2.0.zip)

**Comment by NewJumper** [comment]
this mod is called Deeper and Darker, not Deeper Dark. You're asking in the wrong place

**Comment by Creativious** [comment]
Oops sorry about that
