### ISSUE TITLE
overworld music plays in the otherisde

### ISSUE THREAD

**Issue by Omega58** [KyaniteMods/DeeperAndDarker#332]
**Minecraft Version**: 1.20.1
**Mod Version**: 1.2.1
**Mod Loader**: forge

**Description**:
So I was playing creative mode and exploring the dimension, and then overworld music started playing. the only way to listen to the mod's music in creative mode is to use ./playsound deeperdarker:music.otherside (insert the biome name here as there's music for all 3 biomes).

**To Reproduce**:
1. play in creative mode
2. go to the dimension
3. wait until music starts playing

**Screenshots**:

**Additional context**:
idk if it fits here, but i have the same problem with the undergarden so it could possibly be a vanilla or forge bug.

**Comment by NewJumper** [comment]
this should be fixed in the next update, but will test

**Comment by NewJumper** [comment]
fixed in 1.3
