### ISSUE TITLE
Warden equipment explosion resistance

### ISSUE THREAD

**Issue by SarixInTheHouse** [KyaniteMods/DeeperAndDarker#334]
**Description**:
I think the warden armor, as a dropped item, should be resistant to explosions.

Like the Netherite armor, it cant be destroyed by lava. Since it is an upgrade, and a hard one to get, i think the item should be unable to be deleted by explosions.

**Additional context**:
Im requesting this because of the insane frustration that losing it causes.

I had a set of highly enchanted warden armor. In a fight against a warden I died. I got there fast enough to retrieve my items, all items were there except the armor. I also didnt see any mobs that may have picked it up.

The only theory I have is that the sonic shriek causes an explosion, and explosions can delete item. I tested in a creative world to confirm that the warden armor can be destroyed by an explosion.

**Comment by NewJumper** [comment]
but so can other items. we dont plan on making the armor explosion resistant
