### ISSUE TITLE
Soul Elytra boost not working with Elytra Slot mod

### ISSUE THREAD

**Issue by kapuchai** [KyaniteMods/DeeperAndDarker#335]
**Minecraft Version**: 1.20.1
**Mod Version**: 1.3.0
**Mod Loader**: fabric

**Description**:
Soul Elytra boost is not working when Soul Elytra is placed in the slot provided by Elytra Slot mod.

**To Reproduce**:
1. Install Elytra Slot mod: https://modrinth.com/mod/elytra-slot
2. Put Soul Elytra in elytra slot
3. Try using the boost

**Screenshots**:

**Additional context**:
Add any other context about the problem here: crash reports, logs, and any other details.

**Comment by Pedro270707** [comment]
It does work in 1.20.1 for me, what key did you try binding it to?

**Comment by kapuchai** [comment]
As in my example, I tried to bind it to left CTRL. And to make sure, I also tried other keys.

**Comment by kapuchai** [comment]
Okay, I figured it out. It was the Elytra Slot mod. For some reason when Soul Elytra is placed in the slot said mod provides it doesn't work at all. Otherwise works as intended, sorry for the lack of testing.

**Comment by Pedro270707** [comment]
It seems like that mod has compatibility with Deeper and Darker, so I'd say it's best to wait until they update it

**Comment by Fyoncle** [comment]
Shift + CTRL also doesn't work when it casually binded in the normal chestplate slot, its not related to elytra slot mod, but keybinding doesn't work when you using the elytra slot
