### ISSUE TITLE
Hard Crash on 1.3 (MC 1.20.1)

### ISSUE THREAD

**Issue by NolanHewitt** [KyaniteMods/DeeperAndDarker#336]
[crash-2024-08-21_12.14.34-server.txt](https://github.com/user-attachments/files/16695674/crash-2024-08-21_12.14.34-server.txt)

Causes an extreme hard crash when loading into the dimension. Java itself sometimes stops functioning entirely until a full PC reboot is performed. Happens as soon as I enter a portal to the otherside. 1.2.6 has no issues.

**Comment by Pedro270707** [comment]
I've already tried fixing this multiple times yet it keeps coming back, I'll try again

**Comment by NolanHewitt** [comment]
I appreciate the work you put into this mod. Thank you.

**Comment by Pedro270707** [comment]
Does it still happen in 1.3.1?

**Comment by NolanHewitt** [comment]
I tried it again with 1.3.1 and so far this issue seems like its solved!

**Comment by Pedro270707** [comment]
Alright, I'll close this then, thank you!
