### ISSUE TITLE
Armors/Resistance effect does not work

### ISSUE THREAD

**Issue by Tidoto** [KyaniteMods/DeeperAndDarker#340]
**Minecraft Version**: 1.21
**Mod Version**: 1.3.0
**Mod Loader**: neoforge 21.0.167

**Description**:
any level of resistance effect does absolutely nothing

/effect give @e minecraft:resistance infinite 5

**Screenshots**:
https://youtu.be/-_5DO3xCQFM
Link to video showing error

**Additional context**

**Comment by Tidoto** [comment]
it also turns out that having it turned on removes any armor effect, meaning no matter whjat armor you or any mobs have, theyll deal and take full damage

**Comment by Gbergz** [comment]
Is this supposed to be fixed? Couldn't find anything about it, latest version of the mod (v1.3.2) still makes armor act like it has 0 protection values etc.
