### ISSUE TITLE
Crash when searching for armor in creative menu or when taking resonance armor from creative menu. [Fabric 1.20.1]

### ISSUE THREAD

**Issue by NolanHewitt** [KyaniteMods/DeeperAndDarker#341]
When placing the resonance helmet in my inventory in creative mode I got a sever crash. I tried again and searched for an iron helmet in the creative menu to see if making the helmet and getting it that way caused a crash, and it crash while typing in iron helmet in the menu. I made a new world to test it again but it no longer crashes so I'm not sure if it was a one-off strange issue or what. I do have the log.
[crash-2024-08-23_02.57.40-server.txt](https://github.com/user-attachments/files/16725615/crash-2024-08-23_02.57.40-server.txt)

**Comment by Pedro270707** [comment]
It's completely unrelated, the log says that it crashed in a world chunk tick
