### ISSUE TITLE
Resonarium Armor doesn't give immunity to damage [Fabric 1.20.1]

### ISSUE THREAD

**Issue by NolanHewitt** [KyaniteMods/DeeperAndDarker#342]
The update for this mod said this armor should give complete reduction from damage with all 4 pieces, but it seems to just function like regular armor with no unique effects. Unless maybe I'm just misunderstanding how its supposed to work?

**Comment by Pedro270707** [comment]
Updated in 1.3.2 to match (Neo)Forge https://github.com/KyaniteMods/DeeperAndDarker/commit/44cc931ca4678efa2c8421ce54f40839badfdefc

**Comment by Jakok24** [comment]
its complete immunity to warden attacks
