### ISSUE TITLE
Tags not properly updated to 1.21

### ISSUE THREAD

**Issue by Shnupbups** [KyaniteMods/DeeperAndDarker#344]
**Minecraft Version**: 1.21.x
**Mod Version**: 1.3.1
**Mod Loader**: neoforge/forge/fabric

**Description**:
As part of 1.21, Mojang changed the directories for various tags to use singular names instead of plural.

Your mod uses tags in one or more of the old directories that was changed! This means those tag files will no longer load in 1.21 unless you update the directories!

The affected directories and their new counterparts are:
* `tags/blocks` -> `tags/block`
* `tags/items` -> `tags/item`
* `tags/entity_types` -> `tags/entity_type`
* `tags/fluids` -> `tags/fluid`
* `tags/game_events` -> `tags/game_event`

Please ensure that any of these that you are using is updated to the new name in all namespaces (including your own, `minecraft`, and `c`).

**Comment by NewJumper** [comment]
why did you target neo, forge, fabric. Dont just assume because one version doesnt do it, all versions dont. Also, I assume you're talking about fabric?

**Comment by Shnupbups** [comment]
This is a vanilla change in 1.21. It affects every mod, regardless of loader.

Amusing that you write "Don't just assume" and then immediately follow it with "Also I assume you're talking about fabric"...

**Comment by NewJumper** [comment]
As modders, we are well aware of what changes Minecraft does. However, your issue made it seem like it was an issue with **all** the modloaders, which it wasnt.

**Comment by Pedro270707** [comment]
Fixed https://github.com/KyaniteMods/DeeperAndDarker/commit/ee623c8882be9c289f611906cf06b9728698e588
Thanks for reporting!
