### ISSUE TITLE
The mod doesnt work well on 1.21 fabric. 

### ISSUE THREAD

**Issue by pvelitchkov** [KyaniteMods/DeeperAndDarker#346]
**Minecraft Version**: 1.21
**Mod Version**: 1.3.0
**Mod Loader**: fabric loader: 0.16.0-1.21

**Description**:

I generated a couple of worlds and most of them the new dimension "The Otherside" is generated really wacky. The biomes are generated by a couple of blocks and thats it. There is also no ancient temple in all the seeds I tried. Also the mobs are killing each other for some really strange reason.

**To Reproduce**:
1. Go to the Otherside
2. Everything looks unfinished

------------------------------------------------------------------------------------------------------------------------------------------------------
![2024-08-25_18 15 06](https://github.com/user-attachments/assets/56c6e97a-8299-4779-bb8a-fb3a56a5d766)

**Additional context**:
Everything else works good with the mod but when it comes down to the new dimension it just gets really bad. I also tried the Deeper darker mod without any additional mods but it didnt solve the problem. So I would be really pleased if you can help me out with this.
Thanks in advance!

**Comment by Pedro270707** [comment]
What exactly do you mean by unfinished?

**Comment by Pedro270707** [comment]
The ancient temple bug has been fixed: https://github.com/KyaniteMods/DeeperAndDarker/commit/ee623c8882be9c289f611906cf06b9728698e588
Also, if you mean shattered attacking sludges, that is intentional

**Comment by Pedro270707** [comment]
I just realized what you meant by "mobs attacking themselves," that was fixed in 1.3.2 as well: https://github.com/KyaniteMods/DeeperAndDarker/commit/f5a1897dcd8fa56edcaac8a66c6a15c4fe198f02 https://github.com/KyaniteMods/DeeperAndDarker/commit/0ed9ab7c5109fa68bf629623255abc052a1173ed
