### ISSUE TITLE
No armor protection or shield can't block attack, from any damage (Neoforge)

### ISSUE THREAD

**Issue by SkyRunner55** [KyaniteMods/DeeperAndDarker#347]
**Minecraft Version**: 1.21.1
**Mod Version**: 1.3
**Mod Loader**: Neoforge 21.1.26

**Description**:
No armor protection or shield can't block attack against all damage

**To Reproduce**:
You just have to be hit with the mod enable (tested with only this mod)
On Hard diffculty, Equip some netherite armor & block with a shield with a skeleton shooting at you

**Comment by NewJumper** [comment]
#340
