### ISSUE TITLE
Warden does not drop Carapace and heart when croptopia is installed

### ISSUE THREAD

**Issue by LatiosAeon** [KyaniteMods/DeeperAndDarker#348]
**Minecraft Version**: 1.21
**Mod Version**: 1.3.1
**Mod Loader**: fabric

**Description**:
I've done the painfully tedious task of finding out why I couldn't get the carapace and warden heart to drop and its caused by croptopia, that mod should not alter anything to do with the deep dark or warden but for some reason, having it installed prevents the warden drops for working correctly, tested with all 250 mods and its only that one causing it.
Will make a bug report on their mod page if its something on their end.

**To Reproduce**:
1. Install only deeper and darker and croptopia
2. kill a warden
3. does not drop additional loot, only a catalyst
4. remove croptopia, heart and carapace now drop when killing wardens

**Screenshots**:
Not required

**Additional context**:
??

**Comment by Pedro270707** [comment]
Fixed https://github.com/KyaniteMods/DeeperAndDarker/commit/1b2d65d21cd96db685530d0a85d1670cc7b4f532
