### ISSUE TITLE
Temples not Spawning

### ISSUE THREAD

**Issue by DreezyMoto** [KyaniteMods/DeeperAndDarker#349]
**Minecraft Version**: 1.21.1
**Mod Version**: 1.3.1
**Mod Loader**: fabric

**Description**:
Temples just spawn as hole in the ground. Did the /Locate command to find one for testing and teleported to it and this is what it considers a temple. (See Screenshot)

**Screenshots**:
![image_2024-08-26_193059982](https://github.com/user-attachments/assets/e5ba7871-b6ae-417d-b8b1-4ae88ae35cd9)

**Comment by Pedro270707** [comment]
Fixed in 1.3.2 already

**Comment by DreezyMoto** [comment]
yeah sick update release
