### ISSUE TITLE
Armors now provide no protection when the mod is enabled

### ISSUE THREAD

**Issue by Seraphim1998** [KyaniteMods/DeeperAndDarker#350]
**Minecraft Version**: 1.21.1
**Mod Version**: 1.21.1
**Mod Loader**: neoforge

**Description**:
The 1.21.1 release causes armor (both vanilla and modded) provides no protection, even if the armor value can still be shown, wearing the armor suffers the same damage as naked.

**To Reproduce**:

I disabled all the armor and vanilla extension mods beside this one and found out it was this mod causing the problem. I tested by swimming in lava with or without armor and the result clearly revealed there's no damage deduction even with a diamond set when this mod is enabled.

**Comment by NewJumper** [comment]
why do people never check for duplicates 💀

**Comment by NewJumper** [comment]
#340

**Comment by NolanHewitt** [comment]
It doesn't look like a duplicate 💀 The resistance effect works and armor provides its normal protection. The supposed invulnerability effect from this armor just didn't work.
