### ISSUE TITLE
[Feature] Allow the Soulbound Enchantment to simply be fully disabled

### ISSUE THREAD

**Issue by Anonyku05** [KyaniteMods/DeeperAndDarker#352]
**Description**:
Basically in the title, i know technically we only have to avoid using it, but still would be a nice feature that shouldn't be hard to implement in theory.

**Comment by Pedro270707** [comment]
We don't have that enchantment

**Comment by Anonyku05** [comment]
Indeed, sorry for the bothering, haven't noticed the original mod
