### ISSUE TITLE
Adding this mod in Minecraft 1.21.1 will cause the armor provided by the equipment to take effect abnormally, hope to fix it

### ISSUE THREAD

**Issue by uid114514** [KyaniteMods/DeeperAndDarker#353]
**Minecraft Version**: 1.21.1
**Mod Version**: 1.3
**Mod Loader**: neoforge

**Description**:
Adding this mod in Minecraft 1.21.1 will cause the armor provided by the equipment to take effect abnormally.

**To Reproduce**:
Just add it to my mods folder。

**Screenshots**:

**Additional context**:

**Comment by NewJumper** [comment]
fixed in 1.3.1
