### ISSUE TITLE
soul elytra Crashing

### ISSUE THREAD

**Issue by HarryBrazzers** [KyaniteMods/DeeperAndDarker#354]
**Minecraft Version**: 1.20.1
**Mod Version**: 1.3.0
**Mod Loader**: forge

**Description**:
 So I'm playing on a server. I went to spawn in the soul elytra wings To try them out and they Cause my game crash [not the server just my game] And I'll go to join the server again, but I can't because it instantly crashes me because they are still in my inventory. i know how to fix t so i can join the server again but it Crashes anyone that has them wings in their inventory.
**To Reproduce**:

For me, it's just having the wings in the inventory

**Additional context**:
Add any other context about the problem here: crash reports, logs, and any other details.

[2024-08-30-12.log](https://github.com/user-attachments/files/16823590/2024-08-30-12.log)

**Comment by NewJumper** [comment]
use the latest version of the mod

**Comment by HarryBrazzers** [comment]
> use the latest version of the mod

I don’t see an update for forge 1.20.1? Am I blind?  It still says the latest one is 1.3

**Comment by NewJumper** [comment]
https://www.curseforge.com/minecraft/mc-mods/deeperdarker/files/5675456
