### ISSUE TITLE
Allow adding armor upgrade options

### ISSUE THREAD

**Issue by twenty41** [KyaniteMods/DeeperAndDarker#355]
**Description**:
In my modpack I have Enderite, which is one better than Netherite. It would be nice to be able to add those to the Warden armor upgrade recipes to maintain the natural armor progression flow, diamond > netherite > enderite > warden. 

**Additional context**:
I just imagine a config section where I could add `enderitemod:enderite_helmet` to the Warden Helmet recipe, `enderitemomd:enderite_chestplate` to the Warden Chestplate recipe, etc

edit
I am stupid and discovered CraftTweaker after posting this. Maybe it would be cool to include this natively so I'll leave this open but I found a method

**Comment by NewJumper** [comment]
we dont plan in adding this, but you can use craft tweaker
