### ISSUE TITLE
Sludge don't spawn and can't be place with commands or spawn egg

### ISSUE THREAD

**Issue by NolanHewitt** [KyaniteMods/DeeperAndDarker#356]
**Minecraft Version**: 1.20.1
**Mod Version**: 1.3.2
**Mod Loader**: fabric

**Description**:
They either instantly despawn or can't be place at all. They don't appear for even a single frame. Not sure if this is related to #343

**Comment by NewJumper** [comment]
are you in peaceful mode?

**Comment by NolanHewitt** [comment]
No, I had it set to hard mode while testing. It also occurs on easy and normal mode.

**Comment by Pedro270707** [comment]
What's your mod list?

**Comment by NolanHewitt** [comment]
[latest.log](https://github.com/user-attachments/files/18131446/latest.log)
I've got a pretty big mod list, it does seem to be an issue with this mod and another mod. Later today or early morning tomorrow I'll test all my mods to find the one causing the issue.

**Comment by NolanHewitt** [comment]
Ok, I remember this happening in normal world types but maybe I'm misremembering, but right now it looks like this is being caused by https://modrinth.com/mod/superflat-world-no-slimes and only in superflat worlds.

Since this only effects superflat worlds no I don't think this is a major issue so I'll close it. Might be worth looking into why this happens though in case the sludges being considered slimes effects compatibility with other potential mods.
