### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Hanwei233** [KyaniteMods/DeeperAndDarker#360]
**Minecraft Version**: 1.20.1
**Mod Version**: 1.3.1
**Mod Loader**: forge

**Description**:

**To Reproduce**:
2. Click on '...'
3. Scroll down to '...'

**Screenshots**:

**Additional context**:
[crash-2024-09-05_04.02.48-server.txt](https://github.com/user-attachments/files/16880412/crash-2024-09-05_04.02.48-server.txt)

**Comment by NewJumper** [comment]
this is not a issue on our end. open a report on sculkhorde's issue page
