### ISSUE TITLE
Outdated Mekanism integration

### ISSUE THREAD

**Issue by LatvianModder** [KyaniteMods/DeeperAndDarker#370]
**Minecraft Version**: 1.21.1
**Mod Version**: 1.3.2
**Mod Loader**: neoforge

**Description**:
When loaded in modpack with mekanism 7.7+ it produces hundreds of broken recipe errors

Current generated recipe format:

```json
{
	"type": "mekanism:enriching",
	"input": {
		"ingredient": {
			"item": "deeperdarker:sculk_stone_brick_slab"
		}
	},
	"output": {
		"item": "deeperdarker:polished_sculk_stone_slab"
	},
	"neoforge:conditions": [
		{
			"type": "neoforge:mod_loaded",
			"modid": "mekanism"
		}
	]
}
```

What it should look like:

```json
{
	"type": "mekanism:enriching",
	"input": {
		"count": 1,
		"item": "minecraft:diorite_stairs"
	},
	"output": {
		"count": 1,
		"id": "minecraft:polished_diorite_stairs"
	}
}
```

And many many others

**Comment by suerion** [comment]
On Minecraft Fabric it gaves me a lot of receips errors -> 

https://mclo.gs/cX8M9H0

@NewJumper
