### ISSUE TITLE
Entering the DeepDark dimension causes CPU to reduce to near 0, effectively crashing the server without an actual crash.

### ISSUE THREAD

**Issue by EliasRipley** [KyaniteMods/DeeperAndDarker#373]
**Minecraft Version**: 1.20.1
**Mod Version**: 1.3.2
**Mod Loader**: forge

**Description**:
Entering the dimension causes server to report:
[Worker-Main-4/WARN] [minecraft/UniformHeight]: Empty height range: [0 above bottom--8 absolute]
The CPU levels drop to near 0 effectively causing a crash without an actual crash.
Leaving the server hanging for a good 10 mins hoping for an actual crash so a report could be made, but it does not, I just have to manually kill the server. (Stop doesn't work.)

**To Reproduce**:
Unknown, just enter the dimension on our server.

**Screenshots**:

**Additional context**:
Happy to share our server's modpack with you.
Our server uses Tectonic as our terrain gen mod. Perhaps an incompatibility with this is likely an issue when considering the error?
They seem to have recently been making changes to an 'increased_height' value according to their changelogs?

**Comment by EliasRipley** [comment]
[2024-09-18-1.log.gz](https://github.com/user-attachments/files/17036552/2024-09-18-1.log.gz)

Here's a log of me entering the dimension with a command. I did this after one of our players entered for the first time and the issue was first seen. (Forcing us to kill the server.) I used a ftb command: /tp_offline to get us both to safety and have used dimensionaccessmanager mod to lock people from being able to enter the dimension until a solution is found.

**Comment by EliasRipley** [comment]
Added to additional context:
Our server uses Tectonic as our terrain gen mod. Perhaps an incompatibility with this is likely an issue when considering the error?
They seem to have recently been making changes to an 'increased_height' value according to their changelogs?

**Comment by NewJumper** [comment]
I'm unable to recreate this with just Deeper and Darker, so it may be a compatibility issue.
Could you try recreating this with just Deeper and Darker? If not, could you send the mods you used?

**Comment by EliasRipley** [comment]
Heya. So this is our client side modpack.
Let me know if you are still unable to replicate with this and I'll gather our server side only mods into a zip for you too when I'm home.
https://www.curseforge.com/minecraft/modpacks/the-project-server-modpack

**Comment by EliasRipley** [comment]
[Server Only List.zip](https://github.com/user-attachments/files/17047347/Server.Only.List.zip)

... and here's that server only side.

**Comment by NewJumper** [comment]
the server and client should have the same mods (except for client specific mods)

**Comment by EliasRipley** [comment]
> the server and client should have the same mods (except for client specific mods)

Well all the ones that are server side only are listed as such on their mod pages.

**Comment by NewJumper** [comment]
but you also need content mods as well, Deeper and Darker included

**Comment by EliasRipley** [comment]
> but you also need content mods as well, Deeper and Darker included

Right...? Wait are you thinking that my server only mods zip is all that we have on the server? That's the mods additional to the client pack. 😆 Only server, not 'the only things on the server'. How would someone have even travelled to the deepdark if we didn't have it on the server? 😂

**Comment by EliasRipley** [comment]
Decided to try looking into your files.
The current noise generator configuration is perhaps limiting terrain generation depth?
NoiseSettings.create(0, 128, 1, 2)
Mod expects some features as low as -92?

**Comment by NewJumper** [comment]
Which mod?

**Comment by NewJumper** [comment]
There really shouldn't be any features being placed in the Otherside except from those from our mod

**Comment by EliasRipley** [comment]
> Which mod?

DeeperDarker.

**Comment by NewJumper** [comment]
Except deeper darker doesnt generate enything below 0y

**Comment by EliasRipley** [comment]
> Except deeper darker doesnt generate enything below 0y

Oh. In that case I don't have a clue.
Have tried leaving the server hanging longer since hoping for an actual crash but no luck on that.

**Comment by NewJumper** [comment]
does the server run fine when you're not in the Otherside dimension?

**Comment by EliasRipley** [comment]
> does the server run fine when you're not in the Otherside dimension?

Smooth as butter. Other dimensions too.

**Comment by OminousSun** [comment]
Hello, I was having a similar issue with Geophilic reforged, once I removed it seems to work just fine. maybe it's a world generation mod that's causing the issue

**Comment by EliasRipley** [comment]
> Hello, I was having a similar issue with Geophilic reforged, once I removed it seems to work just fine. maybe it's a world generation mod that's causing the issue

Seems most likely. The tectonic dev has said they have no interest in adding this to their task lists unfortunately. Would be interested to know if any other tectonic users have DnD installed without this issue.

**Comment by NewJumper** [comment]
it's most likely a tectonic issue because solo testing works fine.

**Comment by OminousSun** [comment]
Hello, after I did some further testing, I have come to find out that the mod that was causing me issues within the Deeper and Darker biome was actually [Majrusz's Accessories](https://www.curseforge.com/minecraft/mc-mods/majruszs-accessories)
The profile I used to test this should be right here: [forge test.zip](https://github.com/user-attachments/files/17143771/forge.test.zip)

Steps to replicate:

1. Have a 1.20.1 forge mod pack with forge version 47.3.7
2. Install the following mods:
- Deeper and Darker
- Majrusz Library
- Majrusz's Accessories
- FerriteCore (for testing purposes, shouldn't affect the issue)
- ModernFix (for testing purposes, shouldn't affect the issue)
- spark (for testing purposes, shouldn't affect the issue)
3. Create a new world and locate an ancient city
4. Open the portal and go through it
5. Wait until the game is unresponsive (you can tell this is the case by dropping items, and checking if the dropped items disappear)
6. Wait for about 1-2 minutes watching over the Logs (should be on Curse Forge next to content)
7. Once the error is displayed, kill Minecraft with the task manager.

P.S: This issue reminded me of a [deadlock](https://www.geeksforgeeks.org/introduction-of-deadlock-in-operating-system/), which is very strange since I never thought I'd see it in these two mods of all things(Finally get to apply what I learned in my OS class)

**Comment by EliasRipley** [comment]
> Hello, after I did some further testing, I have come to find out that the mod that was causing me issues within the Deeper and Darker biome was actually [Majrusz's Accessories](https://www.curseforge.com/minecraft/mc-mods/majruszs-accessories) The profile I used to test this should be right here: [forge test.zip](https://github.com/user-attachments/files/17143771/forge.test.zip)
> 
> Steps to replicate:
> 
> 1. Have a 1.20.1 forge mod pack with forge version 47.3.7
> 2. Install the following mods:
> 
> * Deeper and Darker
> * Majrusz Library
> * Majrusz's Accessories
> * FerriteCore (for testing purposes, shouldn't affect the issue)
> * ModernFix (for testing purposes, shouldn't affect the issue)
> * spark (for testing purposes, shouldn't affect the issue)
> 
> 3. Create a new world and locate an ancient city
> 4. Open the portal and go through it
> 5. Wait until the game is unresponsive (you can tell this is the case by dropping items, and checking if the dropped items disappear)
> 6. Wait for about 1-2 minutes watching over the Logs (should be on Curse Forge next to content)
> 7. Once the error is displayed, kill Minecraft with the task manager.
> 
> P.S: This issue reminded me of a [deadlock](https://www.geeksforgeeks.org/introduction-of-deadlock-in-operating-system/), which is very strange since I never thought I'd see it in these two mods of all things(Finally get to apply what I learned in my OS class)

Wow. Amazing work. Would not have thought Accessories could have been the culprit. Do you think it's trying to spawn in those mimic chest structures in DnD?
I'll pop into their discord and let them know.

**Comment by EliasRipley** [comment]
Looks like you've got that covered already.
https://github.com/Majrusz/MajruszsAccessories/issues/65

**Comment by NewJumper** [comment]
this does seem to be more of a Majrusz's Accessories's issue
