### ISSUE TITLE
Pressing f3 in the "otherside" causes game to crash when Biomes O' Plenty is installed.

### ISSUE THREAD

**Issue by YourfriendTutu** [KyaniteMods/DeeperAndDarker#382]
**Minecraft Version**: 1.21.1
**Mod Version**: 1.3.2
**Mod Loader**: neoforge

**Description**:
Mod incompatibility with Biomes O' Plenty causes a crash whenever the client presses f3 in the "otherside" dimension.

**To Reproduce**:
1. Install Biomes O' Plenty & Deeper and Darker together
2. Go to the "Otherside" dimension
3. Press f3
4. Game crashes with nullpointerexception.

If this is an issue where the two mods cannot coexists then I will forego one of them respectively. Else, I would like to have both mods be compatible with each other.

**Comment by NewJumper** [comment]
send the crash report

**Comment by YourfriendTutu** [comment]
> send the crash report

[crash-2024-10-24_23.52.07-fml.txt](https://github.com/user-attachments/files/17532032/crash-2024-10-24_23.52.07-fml.txt)

**Comment by YourfriendTutu** [comment]
> send the crash report

[crash-2024-10-24_16.51.51-client.txt](https://github.com/user-attachments/files/17532033/crash-2024-10-24_16.51.51-client.txt)

**Comment by NewJumper** [comment]
this is not a deeper darker issue. this is a terrablender issue. open a post for them

**Comment by Satherov** [comment]
https://github.com/Glitchfiend/TerraBlender/issues/183

Been reported by us already, we've downgraded to 4.1.0.0 until it's fixed, I recommend you do the same
