### ISSUE TITLE
Failed to load textures

### ISSUE THREAD

**Issue by CaoTrongThang** [KyaniteMods/DeeperAndDarker#383]
**Minecraft Version**: 1.20.1
**Mod Version**: 1.3.2.1
**Mod Loader**: fabric

**Description**:
The textures of armors are pink, tools and weapons are still normal

**To Reproduce**:
I just downloaded mods and start it.

**Screenshots**:
![image](https://github.com/user-attachments/assets/36101e31-f4f2-4963-b607-0dccdea44642)
![image](https://github.com/user-attachments/assets/2124fa39-4e39-45ab-86e8-45d163bbb635)
jesus I look funny

**Additional context**:
here's the mod list, there're a lot of mods.
[mod list.txt](https://github.com/user-attachments/files/17537120/mod.list.txt)

**Comment by CaoTrongThang** [comment]
**Minimal tested**

![image](https://github.com/user-attachments/assets/436258a3-23d2-4f14-a51d-509ee8d90a49)
![image](https://github.com/user-attachments/assets/b1d8a222-e564-4b27-8138-686e56cf838b)

**Comment by NewJumper** [comment]
duplicate of #381

**Comment by galenvares** [comment]
"""Solution""":  

https://github.com/KyaniteMods/DeeperAndDarker/issues/381#issuecomment-2485021001
