### ISSUE TITLE
Incompatibility with Eternal Starlight mod

### ISSUE THREAD

**Issue by ndujinski** [KyaniteMods/DeeperAndDarker#385]
**Minecraft Version**: 1.21
**Mod Version**: 1.3.1
**Mod Loader**: Fabric

**Description**:
Game crashes when placing Deeper and Darker boats in ether from Eternal Starlight (vanilla boats just break).
(Eternal Starlight version used: 0.1.5 Fabric)

**To Reproduce**:
1. Go to an ether lake in the Starlight dimension or make one using ether buckets in any dimension.
2. Use boat from Deeper and Darker mod on ether.

**Comment by Pedro270707** [comment]
I tried both the newest version (0.1.18) and 0.1.5 and neither crashed. I tried with all four variants (echo boat, bloom boat, echo boat with chest, and bloom boat with chest). Maybe it's already fixed in 1.3.2.1, could you try that version?
