### ISSUE TITLE
Bug of the warden helmet

### ISSUE THREAD

**Issue by ThanhLoc0910** [KyaniteMods/DeeperAndDarker#394]
**Minecraft Version**: 1.20.1
**Mod Version**: any version
**Mod Loader**: forge

**Description**:
I search wiki that said when equip the warden helmet, but there is no night vision effect when i equip it.

**Screenshots**:
![image](https://github.com/user-attachments/assets/cbe19f7d-f420-436f-84a9-6764d16af42d)

**Comment by Pedro270707** [comment]
It doesn't give night vision, only immunity to Darkness and Blindness
