### ISSUE TITLE
Are there only natural ancient vases that have a probability of appearing Sculk Leeches and stalkers (boss) after being destroyed?

### ISSUE THREAD

**Issue by Cindystick** [KyaniteMods/DeeperAndDarker#395]
I found that only naturally spwaning ancient vases can produce leeches and stalkers, also known as bosses. They can not reproduce after collecting or digging, despite of smithing touch , and have the same mechanism as a Sculk Shrieker summoning a warden. Right？

**Comment by Pedro270707** [comment]
Yes
