### ISSUE TITLE
Missing textures on Resonarium Armor

### ISSUE THREAD

**Issue by MagicFlavel** [KyaniteMods/DeeperAndDarker#396]
**Minecraft Version**: 1.20.1
**Mod Version**: 1.3.2.1-fabric+1.20
**Mod Loader**: Modrinth
**Description**: Any piece of the Resonarium armor shows as bright pink and or black texture.
**To Reproduce**:
1. Install mod/required mods for install 
2. Open game/World
3. put armor on
4. see error
**Screenshots**:
![Capture](https://github.com/user-attachments/assets/d56afe2c-473e-4674-8cee-4d3dd1aaf646)

**Comment by Pedro270707** [comment]
Already fixed in future release https://github.com/KyaniteMods/DeeperAndDarker/commit/6003ba5253eaa02d51a3304b801d8459e98dfb2d
