### ISSUE TITLE
{better trims incompatible]Crashed while taming Sculk Snapper with a enchanted Netherite Chestplate)

### ISSUE THREAD

**Issue by Cindystick** [KyaniteMods/DeeperAndDarker#398]
**Minecraft Version**: 1.21.1
**Mod Version**: 
deeperdarker-fabric-1.21-1.3.2.1
BetterTrims-3.2.6-fabric+1.21.1

**Mod Loader**: fabric

**Description**:
Once I hold the enchanted Netherite Chestplate and try to tame a Sculk Snapper, it will either become ineffective (as a replacement breastplate), or the game will collapse, or it will flash back after holding it in front of the Sculk Snapper for a period of time.

**To Reproduce**:
1. Go to 'Sculk Snapper'
2. Click on 'the right mouse button'
3. See error

**Screenshots**:

**Additional context**:
[crash-2024-12-05_15.54.12-server.txt](https://github.com/user-attachments/files/18019546/crash-2024-12-05_15.54.12-server.txt)
[crash-2024-12-05_15.56.45-server.txt](https://github.com/user-attachments/files/18019547/crash-2024-12-05_15.56.45-server.txt)

**Comment by Pedro270707** [comment]
Unrelated to Better Trims, already fixed in a future update https://github.com/KyaniteMods/DeeperAndDarker/commit/aacc8ae5259e1060f863c818f3322966fe30d33a
