### ISSUE TITLE
Crash with Sculk Snapper

### ISSUE THREAD

**Issue by LufeeSavier** [KyaniteMods/DeeperAndDarker#399]
**Minecraft Version**: 1.21.1
**Mod Version**: 1.3.2.1
**Mod Loader**: fabric

**Description**:
Tamed a Sculk snapper, now I'm receiving tick errors from it. I have other mods so I'm unsure if it's a conflict from those or not

1. Tame a Sculk Snapper
2. Wait a couple of minutes then the game crashes

**Additional context**:
[crash-2024-12-05_22.42.47-client.txt](https://github.com/user-attachments/files/18032590/crash-2024-12-05_22.42.47-client.txt)

**In Case You Don't Want to Open the txt File**

---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 2024-12-05 22:42:47
Description: Ticking entity

java.lang.IllegalStateException: This registry can't create intrusive holders
	at net.minecraft.class_2370.method_40269(class_2370.java:369)
	at com.kyanite.deeperdarker.content.entities.SculkSnapper.method_5773(SculkSnapper.java:113)
	at net.minecraft.class_638.method_18646(class_638.java:278)
	at net.minecraft.class_1937.method_18472(class_1937.java:498)
	at net.minecraft.class_638.method_32124(class_638.java:261)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_638.method_18116(class_638.java:257)
	at net.minecraft.class_310.method_1574(class_310.java:1956)
	at net.minecraft.class_310.method_1523(class_310.java:1246)
	at net.minecraft.class_310.method_1514(class_310.java:882)
	at net.minecraft.client.main.Main.main(Main.java:256)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_2370.method_40269(class_2370.java:369)
	at com.kyanite.deeperdarker.content.entities.SculkSnapper.method_5773(SculkSnapper.java:113)
	at net.minecraft.class_638.method_18646(class_638.java:278)
	at net.minecraft.class_1937.method_18472(class_1937.java:498)
	at net.minecraft.class_638.method_32124(class_638.java:261)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_638.method_18116(class_638.java:257)

-- Entity being ticked --
Details:
	Entity Type: deeperdarker:sculk_snapper (com.kyanite.deeperdarker.content.entities.SculkSnapper)
	Entity ID: 250
	Entity Name: Sculk Snapper
	Entity's Exact location: -2918.09, -52.00, -3052.42
	Entity's Block location: World: (-2919,-52,-3053), Section: (at 9,12,3 in -183,-4,-191; chunk contains blocks -2928,-64,-3056 to -2913,319,-3041), Region: (-6,-6; contains chunks -192,-192 to -161,-161, blocks -3072,-64,-3072 to -2561,319,-2561)
	Entity's Momentum: 0.00, -0.07, 0.00
	Entity's Passengers: []
	Entity's Vehicle: null
Stacktrace:
	at net.minecraft.class_1937.method_18472(class_1937.java:498)
	at net.minecraft.class_638.method_32124(class_638.java:261)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_638.method_18116(class_638.java:257)
	at net.minecraft.class_310.method_1574(class_310.java:1956)
	at net.minecraft.class_310.method_1523(class_310.java:1246)
	at net.minecraft.class_310.method_1514(class_310.java:882)
	at net.minecraft.client.main.Main.main(Main.java:256)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Uptime --
Details:
	JVM uptime: 11711.062s
	Wall uptime: 11680.039s
	High-res time: 11664.685s
	Client ticks: 232952 ticks / 11647.600s
Stacktrace:
	at net.minecraft.class_310.method_1587(class_310.java:2501)
	at net.minecraft.class_310.method_54580(class_310.java:949)
	at net.minecraft.class_310.method_1514(class_310.java:902)
	at net.minecraft.client.main.Main.main(Main.java:256)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Affected level --
Details:
	All players: 1 total; [class_746['LilW3nch'/126, l='ClientLevel', x=-2917.08, y=-52.00, z=-3054.34]]
	Chunk stats: 1089, 656
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,77,0), Section: (at 0,13,0 in 0,4,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 8575227 game time, 9230149 day time
	Server brand: fabric
	Server type: Non-integrated multiplayer server
	Tracked entity count: 164

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, fabric, appleskin, archers, balm-fabric, bclib, bettercombat, betterend, betternether, cardinal-components-base, cardinal-components-entity, cloth-config, customportalapi, deeperdarker, dragonfight, eldritch_mobs, eternal_starlight, extraspellattributes, fabric-api, fabric-api-base, fabric-api-lookup-api-v1, fabric-biome-api-v1, fabric-block-api-v1, fabric-block-view-api-v2, fabric-blockrenderlayer-v1, fabric-client-tags-api-v1, fabric-command-api-v1, fabric-command-api-v2, fabric-commands-v0, fabric-content-registries-v0, fabric-convention-tags-v1, fabric-convention-tags-v2, fabric-crash-report-info-v1, fabric-data-attachment-api-v1, fabric-data-generation-api-v1, fabric-dimensions-v1, fabric-entity-events-v1, fabric-events-interaction-v0, fabric-game-rule-api-v1, fabric-item-api-v1, fabric-item-group-api-v1, fabric-key-binding-api-v1, fabric-keybindings-v0, fabric-lifecycle-events-v1, fabric-loot-api-v2, fabric-loot-api-v3, fabric-message-api-v1, fabric-model-loading-api-v1, fabric-networking-api-v1, fabric-object-builder-api-v1, fabric-particles-v1, fabric-recipe-api-v1, fabric-registry-sync-v0, fabric-renderer-api-v1, fabric-renderer-indigo, fabric-renderer-registries-v1, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-rendering-v0, fabric-rendering-v1, fabric-resource-conditions-api-v1, fabric-resource-loader-v0, fabric-screen-api-v1, fabric-screen-handler-api-v1, fabric-sound-api-v1, fabric-transfer-api-v1, fabric-transitive-access-wideners-v1, fabricloader, forgivingworld, jei, jewelry, mr_dungeons_andtaverns, owo, paladins, playeranimator, polymer-blocks, polymer-core, portablemobs, puffish_attributes, puffish_skills, ranged_weapon_api, reinfchest, reinfcore, rogues, runes, shield_api, spell_engine, spell_power, structure_pool_api, supermartijn642corelib, trinkets, waystones, wizards, wover, wover-block, wover-core, wover-events, wover-generator, wover-preset, wover-surface, wover-ui, wunderlib, xaeroworldmap

-- System Details --
Details:
	Minecraft Version: 1.21.1
	Minecraft Version ID: 1.21.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 21.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 573758256 bytes (547 MiB) / 2147483648 bytes (2048 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 16
	Processor Vendor: GenuineIntel
	Processor Name: 11th Gen Intel(R) Core(TM) i9-11900K @ 3.50GHz
	Identifier: Intel64 Family 6 Model 167 Stepping 1
	Microarchitecture: Rocket Lake
	Frequency (GHz): 3.50
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: NVIDIA GeForce RTX 3060
	Graphics card #0 vendor: NVIDIA
	Graphics card #0 VRAM (MiB): 12288.00
	Graphics card #0 deviceId: VideoController1
	Graphics card #0 versionInfo: 32.0.15.6094
	Memory slot #0 capacity (MiB): 16384.00
	Memory slot #0 clockSpeed (GHz): 2.67
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MiB): 16384.00
	Memory slot #1 clockSpeed (GHz): 2.67
	Memory slot #1 type: DDR4
	Virtual memory max (MiB): 37467.93
	Virtual memory used (MiB): 17487.92
	Swap memory total (MiB): 4864.00
	Swap memory used (MiB): 43.25
	Space in storage for jna.tmpdir (MiB): available: 3317908.50, total: 3815330.00
	Space in storage for org.lwjgl.system.SharedLibraryExtractPath (MiB): available: 3317908.50, total: 3815330.00
	Space in storage for io.netty.native.workdir (MiB): available: 3317908.50, total: 3815330.00
	Space in storage for java.io.tmpdir (MiB): available: 3317908.50, total: 3815330.00
	Space in storage for workdir (MiB): available: 3317908.50, total: 3815330.00
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		appleskin: AppleSkin 3.0.5+mc1.21
		archers: Archers (RPG Series) 2.0.5+1.21.1
			com_github_zsoltmolnarrr_tinyconfig: TinyConfig 2.3.2
		architectury: Architectury 13.0.6
		azurelibarmor: AzureLib Armor 2.3.11
		balm-fabric: Balm 21.0.19
			kuma_api: KumaAPI 21.0.5-SNAPSHOT
		bclib: BCLib 21.0.13
		betterchunkloading: Better chunk loading mod 1.21-4.5
		bettercombat: Better Combat 2.0.3+1.21.1
		betterend: Better End 21.0.11
		betternether: Better Nether 21.0.11
		cloth-config: Cloth Config v15 15.0.140
			cloth-basic-math: cloth-basic-math 0.6.1
		collective: Collective 7.87
		cupboard: cupboard 1.21-2.7
		deeperdarker: Deeper and Darker 1.3.2.1
			customportalapi: Custom Portal Api 0.0.1-beta66-1.21
		default_skill_trees: Default Skill Trees 1.0
		dragonfight: Dragonfight Mod 1.21-4.6
		eldritch_mobs: EldritchMobs 1.16.1
			polymer-blocks: Polymer (Textured Blocks) 0.9.9+1.21
			polymer-core: Polymer (Core) 0.9.9+1.21
				polymer-networking: Polymer (Networking) 0.9.9+1.21
					polymer-common: Polymer (Common) 0.9.9+1.21
						packet_tweaker: Packet Tweaker 0.5.5+1.21
				polymer-registry-sync-manipulator: Polymer (Registry Sync Manipulator) 0.9.9+1.21
			server_translations_api: Server Translations API 2.3.1+1.21-pre2
		eternal_starlight: Eternal Starlight 0.1.15+1.21.1+fabric
		extraspellattributes: Extra RPG Attributes 1.0.4+1.21.1
		fabric-api: Fabric API 0.105.0+1.21.1
			fabric-api-base: Fabric API Base 0.4.42+6573ed8c19
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.68+b559734419
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.29+5bd9f1bc19
			fabric-block-api-v1: Fabric Block API (v1) 1.0.22+0af3f5a719
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.10+6573ed8c19
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.52+0af3f5a719
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.15+6573ed8c19
			fabric-command-api-v1: Fabric Command API (v1) 1.2.49+f71b366f19
			fabric-command-api-v2: Fabric Command API (v2) 2.2.28+6ced4dd919
			fabric-commands-v0: Fabric Commands (v0) 0.2.66+df3654b319
			fabric-content-registries-v0: Fabric Content Registries (v0) 8.0.16+b559734419
			fabric-convention-tags-v1: Fabric Convention Tags 2.0.23+7f945d5b19
			fabric-convention-tags-v2: Fabric Convention Tags (v2) 2.8.0+9d22c5fd19
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.29+0af3f5a719
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.1.28+1daea21519
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 20.2.20+16c4ae2519
			fabric-dimensions-v1: Fabric Dimensions API (v1) 4.0.0+6fc22b9919
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.7.0+2122d82819
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.7.13+ba9dae0619
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.53+6ced4dd919
			fabric-item-api-v1: Fabric Item API (v1) 11.1.0+d5debaed19
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.1.5+3fc0e55219
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.47+0af3f5a719
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.45+df3654b319
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.3.12+6c1df36019
			fabric-loot-api-v2: Fabric Loot API (v2) 3.0.14+3f89f5a519
			fabric-loot-api-v3: Fabric Loot API (v3) 1.0.2+3f89f5a519
			fabric-message-api-v1: Fabric Message API (v1) 6.0.13+6573ed8c19
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 2.0.0+fe474d6b19
			fabric-networking-api-v1: Fabric Networking API (v1) 4.3.0+c7469b2119
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 15.2.0+40875a9319
			fabric-particles-v1: Fabric Particles (v1) 4.0.2+6573ed8c19
			fabric-recipe-api-v1: Fabric Recipe API (v1) 5.0.13+6508971219
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 5.1.3+60c3209b19
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.4.0+c705a49c19
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.7.0+c705a49c19
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.68+df3654b319
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.48+73761d2e19
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.1.6+1daea21519
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.71+df3654b319
			fabric-rendering-v1: Fabric Rendering (v1) 5.0.5+df16efd019
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 4.3.0+8dc279b119
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 1.3.0+5659912919
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.25+8b68f1c719
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.87+b559734419
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.23+6573ed8c19
			fabric-transfer-api-v1: Fabric Transfer API (v1) 5.3.0+d831205f19
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 6.1.0+1daea21519
		fabricloader: Fabric Loader 0.16.5
			mixinextras: MixinExtras 0.4.1
		fixedanvilrepaircost: Fixed Anvil Repair Cost 3.4
		forgivingworld: Forgiving World Mod 1.21-4.7
		java: OpenJDK 64-Bit Server VM 21
		jei: Just Enough Items 19.19.0.220
		jewelry: Jewelry (RPG Series) 2.0.2+1.21.1
		minecraft: Minecraft 1.21.1
		mr_dungeons_andtaverns: Dungeons and Taverns 1-v4.4.4
		owo: oωo 0.12.15+1.21
			blue_endless_jankson: jankson 1.2.2
			io_wispforest_endec: endec 0.1.5
			io_wispforest_endec_gson: gson 0.1.3
			io_wispforest_endec_jankson: jankson 0.1.3
			io_wispforest_endec_netty: netty 0.1.2
		paladins: Paladins & Priests (RPG Series) 2.0.5+1.21.1
		playeranimator: Player Animator 2.0.0-alpha1+1.21
		portablemobs: Portable Mobs 1.2.1+a
		puffish_attributes: Pufferfish's Attributes 0.6.0
		puffish_skills: Pufferfish's Skills 0.13.2
		ranged_weapon_api: RangedWeaponAPI 2.0.4+1.21.1
		reinfchest: Reinforced Chests 3.1.0+1.21.1
			reinfcore: Reinforced Core 4.0.2+1.21.1
		rogues: Rogues & Warriors (RPG Series) 2.0.1+1.21.1
		runes: Runes 1.0.3+1.21.1
		shield_api: Shield API 2.0.2+1.21.1
		skyvillages: Sky Villages 1.0.6
		spell_engine: Spell Engine 1.1.1+1.21.1
		spell_power: Spell Power Attribute 1.0.5+1.21.1
		structure_pool_api: Structure Pool API 1.1.3+1.21.1
		supermartijn642corelib: SuperMartijn642's Core Lib 1.1.17+c
		trinkets: Trinkets 3.10.0
			cardinal-components-base: Cardinal Components API (base) 6.1.0
			cardinal-components-entity: Cardinal Components API (entities) 6.1.0
		waystones: Waystones 21.1.4
		wizards: Wizards (RPG Series) 2.0.2+1.21.1
		wover: WorldWeaver 21.0.13
			wover-biome: WorldWeaver - Biome API 21.0.13
			wover-block: WorldWeaver - Block and Item API 21.0.13
			wover-common: WorldWeaver - Common API 21.0.13
			wover-core: WorldWeaver - Core API 21.0.13
			wover-datagen: WorldWeaver - Datagen API 21.0.13
			wover-events: WorldWeaver - Events API 21.0.13
			wover-feature: WorldWeaver - Feature API 21.0.13
			wover-generator: WorldWeaver - World Generator API 21.0.13
			wover-item: WorldWeaver - Item API 21.0.13
			wover-math: WorldWeaver - Math API 21.0.13
			wover-preset: WorldWeaver - World Preset API 21.0.13
			wover-recipe: WorldWeaver - Recipe API 21.0.13
			wover-structure: WorldWeaver - Structure API 21.0.13
			wover-surface: WorldWeaver - Surface API 21.0.13
			wover-tag: WorldWeaver - Tag API 21.0.13
			wover-ui: WorldWeaver - UI API 21.0.13
		wunderlib: WunderLib 21.0.8
		xaeroworldmap: Xaero's World Map 1.39.0
	Launched Version: fabric-loader-0.16.5-1.21.1
	Launcher name: minecraft-launcher
	Backend library: LWJGL version 3.3.3-snapshot
	Backend API: NVIDIA GeForce RTX 3060/PCIe/SSE2 GL version 3.2.0 NVIDIA 560.94, NVIDIA Corporation
	Window size: 1920x1080
	GFLW Platform: win32
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Is Modded: Definitely; Client brand changed to 'fabric'
	Universe: 400921fb54442d18
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Render Distance: 13/31 chunks
	Resource Packs: vanilla, fabric, appleskin (incompatible), archers, balm-fabric (incompatible), bclib, bettercombat, betterend, betternether, cardinal-components-base, cardinal-components-entity, cloth-config, customportalapi, deeperdarker (incompatible), dragonfight (incompatible), eldritch_mobs, eternal_starlight (incompatible), extraspellattributes, fabric-api, fabric-api-base, fabric-api-lookup-api-v1, fabric-biome-api-v1, fabric-block-api-v1, fabric-block-view-api-v2, fabric-blockrenderlayer-v1, fabric-client-tags-api-v1, fabric-command-api-v1, fabric-command-api-v2, fabric-commands-v0, fabric-content-registries-v0, fabric-convention-tags-v1, fabric-convention-tags-v2, fabric-crash-report-info-v1, fabric-data-attachment-api-v1, fabric-data-generation-api-v1, fabric-dimensions-v1, fabric-entity-events-v1, fabric-events-interaction-v0, fabric-game-rule-api-v1, fabric-item-api-v1, fabric-item-group-api-v1, fabric-key-binding-api-v1, fabric-keybindings-v0, fabric-lifecycle-events-v1, fabric-loot-api-v2, fabric-loot-api-v3, fabric-message-api-v1, fabric-model-loading-api-v1, fabric-networking-api-v1, fabric-object-builder-api-v1, fabric-particles-v1, fabric-recipe-api-v1, fabric-registry-sync-v0, fabric-renderer-api-v1, fabric-renderer-indigo, fabric-renderer-registries-v1, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-rendering-v0, fabric-rendering-v1, fabric-resource-conditions-api-v1, fabric-resource-loader-v0, fabric-screen-api-v1, fabric-screen-handler-api-v1, fabric-sound-api-v1, fabric-transfer-api-v1, fabric-transitive-access-wideners-v1, fabricloader, forgivingworld (incompatible), jei (incompatible), jewelry, mr_dungeons_andtaverns (incompatible), owo, paladins, playeranimator, polymer-blocks, polymer-core, portablemobs, puffish_attributes, puffish_skills, ranged_weapon_api, reinfchest, reinfcore, rogues, runes, shield_api, spell_engine, spell_power, structure_pool_api, supermartijn642corelib, trinkets, waystones (incompatible), wizards, wover, wover-block, wover-core, wover-events, wover-generator, wover-preset, wover-surface, wover-ui, wunderlib, xaeroworldmap (incompatible)
	Current Language: en_us
	Locale: en_US
	System encoding: Cp1252
	File encoding: UTF-8
	CPU: 16x 11th Gen Intel(R) Core(TM) i9-11900K @ 3.50GHz

**Comment by Pedro270707** [comment]
Already fixed in a future version https://github.com/KyaniteMods/DeeperAndDarker/commit/aacc8ae5259e1060f863c818f3322966fe30d33a
