### ISSUE TITLE
Resonarium Armor Missing Texture

### ISSUE THREAD

**Issue by NolanHewitt** [KyaniteMods/DeeperAndDarker#401]
**Minecraft Version**: 1.20.1
**Mod Version**: 1.3.2.1
**Mod Loader**: Fabric

Tested using only Fabric API, owo lib, and deeper and darker 1.3.2.1

![image](https://github.com/user-attachments/assets/94e5b5af-7cc3-4661-9630-4a57a0063fd3)

**Comment by Fyoncle** [comment]
Already fixed on dev version, this issue is duplicate.
