### ISSUE TITLE
Incorrect Warden Helmet Pivot

### ISSUE THREAD

**Issue by SpoderMan3288** [KyaniteMods/DeeperAndDarker#64]
**Description**
The pivot point of the Warden Helmet is off, resulting in the top skin layer of the head poking through the helmet.
**To Reproduce**
1. Enable hat layer
2. Equip the Warden Helmet
3. Look down in 3rd person

**Screenshots**
![image](https://user-images.githubusercontent.com/67495659/186461643-de6557ca-c869-4f0d-99ca-54b8e9f5b699.png)
![image](https://user-images.githubusercontent.com/67495659/186461697-18d1a4d8-e3e7-4d28-b716-b338680d8e80.png)
![image](https://user-images.githubusercontent.com/67495659/186461800-b332c373-e126-407d-be23-db2c694cdec2.png)

**Comment by ForkNSpoon56** [comment]
i have the same issue

**Comment by NewJumper** [comment]
the long-lasting bug has been fixed
