### ISSUE TITLE
Add a config file for altering weapon statistics. 

### ISSUE THREAD

**Issue by purejosh** [KyaniteMods/DeeperAndDarker#68]
If we server admins could have control over the attack damage, attack speed, and durability of the warden tools and armor, I think it will be easier for us to integrate them into our worlds. I've already brought this up in the discord, but I'm filing a github, for officialness. :) 

By far one of the better warden related mods I've ever seen, love the ideas you've done so far.

**Comment by ang-xd** [comment]
Coming in the next major update.

**Comment by nitrodynamite18** [comment]
Implemented in release 1.1.0.
