### ISSUE TITLE
Wrong portal placing

### ISSUE THREAD

**Issue by GatoLeyo** [KyaniteMods/DeeperAndDarker#71]
**Description**
Whenever I go to the otherside or back to the overworld, a new portal is created instead of linking the previous two portals. 

**To Reproduce**
1. Go through the otherside portal multiple times
2. Watch a new portal appear each time

**Comment by NewJumper** [comment]
Could you provide a video of such behavior happening? I cannot seem to replicate it.

**Comment by SpoderMan3288** [comment]
Is this happening on forge or fabric?  I can't seem to replicate it.
