### ISSUE TITLE
Deeper and Darker Texture Update

### ISSUE THREAD

**Issue by DanielArtist3726** [KyaniteMods/DeeperAndDarker#72]
**Description**:
What feature do you think would make Deeper and Darker better? Provide examples of how to obtain it and its uses.

**Additional context**:
Add any other context about the feature here.
[Deeper-and-Darker-Texture-Update.zip](https://github.com/KyaniteMods/DeeperAndDarker/files/9566536/Deeper-and-Darker-Texture-Update.zip)

**Comment by NewJumper** [comment]
Hello! Thanks for your amazing textures! After some decision among the team, we've decided to add a few of your textures, most specifically:

Entities
-
- Shattered

Items
-
- Heart of the Deep
- Reinforced Echo Shard
- Warden Carapace

**Comment by NewJumper** [comment]
More textures were decided to be added!

Blocks
-
- Polished Sculk Stone (used texture, but used old color palette)
- Sculk Gleam
- Sculk Stone (used texture, but used old color palette)
