### ISSUE TITLE
Doesnt work on 1.19

### ISSUE THREAD

**Issue by Gonne5** [KyaniteMods/DeeperAndDarker#74]
The mod doesnt work on forge 41.1.0 version 1.19 of minecraft
When i open the game with the mod installed a message apears saying "Mod file deeperdarker-1.0.0b-1.19.2.jar needs language provider javafml:42 or above to load" "we have found 41"
 
![image](https://user-images.githubusercontent.com/113599138/190386506-b0cf9b9b-ed6d-4c3c-92f3-c6e4b6292a71.png)

**Comment by NewJumper** [comment]
Download the appropriate file [here](https://www.curseforge.com/minecraft/mc-mods/deeperdarker/files/3950086)

**Comment by Gonne5** [comment]
Doesn't work on aternos too. Same error

**Comment by NewJumper** [comment]
That is an issue on how Aternos searches for JAR files. It is an easy fix on our end, so the file will be available soon!

**Comment by Gonne5** [comment]
OK thank u, I will wait for that

**Comment by Gonne5** [comment]
OK thanks, I will wait for that
