### ISSUE TITLE
Wrong trapdoor facing texture

### ISSUE THREAD

**Issue by IwasConfused** [KyaniteMods/DeeperAndDarker#77]
No matter which direction the echo trapdoor faces, the texture is the same when closed, not match the opening texture.

![image](https://user-images.githubusercontent.com/70762136/190884470-89fee0cc-690a-4399-9f0b-cbf713d51ae9.png)
![image](https://user-images.githubusercontent.com/70762136/190884475-cb9535e6-c4ae-4c35-9bc5-e4cbfa40bc70.png)

**Comment by ang-xd** [comment]
Will be fixed in the next major update.
