### ISSUE TITLE
mod doesn't apply itself

### ISSUE THREAD

**Issue by LunarNox** [KyaniteMods/DeeperAndDarker#78]
the mod doesnt load. i place it into my mods folder with only gecklolib and fabric api, and it doesnt add anything. 
[latest.log](https://github.com/KyaniteMods/DeeperAndDarker/files/9595169/latest.log)
![Screenshot 2022-09-18 161020](https://user-images.githubusercontent.com/76565890/190926421-7b68a046-c93e-4a79-91ae-802acbb572d6.png)

**Comment by NewJumper** [comment]
did the game crash the moment you teleported to the ancient city?

**Comment by NewJumper** [comment]
not quite sure i understand the issue here

**Comment by NewJumper** [comment]
Are you sure you downloaded the *fabric* version of the mod?

**Comment by NewJumper** [comment]
You can download it from [here](https://www.curseforge.com/minecraft/mc-mods/deeperdarker/files/3975762)

**Comment by ang-xd** [comment]
Make sure to use the Fabric version, you used Forge.
