### ISSUE TITLE
Issue Encounters

### ISSUE THREAD

**Issue by Daedric-Arbiter** [KyaniteMods/DeeperAndDarker#85]
I have recently encountered several issues with the mod, don't know if it they're intended, or are bugs and issues associated with the mod.

(Also note that I am playing on the Fabric modloader)

First, lets start off with the issue with the upper area of the warden armor not animating with the player sneak animation. (If the image isn't clear, I'll be happy to pinpoint where)
![2022-10-03_16 55 45](https://user-images.githubusercontent.com/114959596/193701341-334c20c2-7c00-483f-8054-baadcaab799e.png)

![2022-10-03_16 55 28](https://user-images.githubusercontent.com/114959596/193701235-ecb18637-448a-4a65-8040-90667b25c629.png)

Another issue I've encountered, is all the mobs (Except the shrieker worm) sounding very like the player hit and death sounds upon being hit and killed by anything (Including iron golems)
![2022-10-03_16 55 11](https://user-images.githubusercontent.com/114959596/193701586-b840d7cd-736a-49c5-ac61-f96437fcaefc.png)

The final issue I've encountered, and I do not know if it is going to be fixed or not cause it is associated with other mods like Charm, Additional Additions, Graveyard, Better Nether and Better End.
The Transmitter is unable to connect to other storage blocks that is from different mods. It only connects to vanilla blocks.
(Again, I'll be happy to pinpoint and show more images if it is not straightforward)
![2022-10-03_16 53 58](https://user-images.githubusercontent.com/114959596/193701992-ae64cb39-1fe9-4997-84ab-c9932e8fe2c2.png)
![2022-10-03_16 54 16](https://user-images.githubusercontent.com/114959596/193702732-33705da8-51e7-40ca-af36-f6f40c7651f2.png)

These issues are not huge deals, but I thought why not report them anyways since they would need to be patched or fixed eventually.
The mod is amazing, and I'll gladly continue to lure out issues, bugs, glitches, etc. no matter how small they are for this mod! ^^

**Comment by ang-xd** [comment]
First issue fixed in upcoming update.
