### ISSUE TITLE
Echo Boat (with Chest) do not drop itself + missing translation string

### ISSUE THREAD

**Issue by Shazuli** [KyaniteMods/DeeperAndDarker#87]
**Description**:
Echo Boats do not drop itself when broken in neither Survival- nor Creative mode. Content of an Echo Boat with Chest do however drop when broken.

Missing translation string for Echo Boat with Chest inventory:
![image](https://user-images.githubusercontent.com/9884180/195603546-55424cfe-686d-4bb1-86a5-db5e7e77cc2a.png)

**Comment by nitrodynamite18** [comment]
Is this on Forge or Fabric?

**Comment by Shazuli** [comment]
Fabric.

**Comment by ang-xd** [comment]
Fixed in 1.1.0 (releasing soon)
