### ISSUE TITLE
Optional power requirement to keep the portal open

### ISSUE THREAD

**Issue by SimonMeskens** [KyaniteMods/DeeperAndDarker#97]
We were talking about potentially making a modpack using D&D, where one of the main mechanics would be that you need to provide continuous power to the portal/some device to keep the portal open, so that the player needs to build a big nuclear reactor complex in the ancient city. Is there some potential way to make an optional power requirement part of opening/keep open the portal?

**Comment by ang-xd** [comment]
Interesting idea. We'll look into it. Thanks for the suggestion.
