### ISSUE TITLE
java.lang.NoSuchMethodError: 'void net.kyrptonaught.customportalapi.api.CustomPortalBuilder.registerPortal()'

### ISSUE THREAD

**Issue by otavio-silva** [KyaniteMods/DeeperAndDarker#98]
**Description**:
It crashes before the game starts.

**To Reproduce**:
1.Install mod
2. Start the game
3. Game crashes

**Additional context**:
The error persists from 1.1.0 to 1.1.1 and 1.1.2
[Log](https://mclo.gs/tU2XhJd)

**EDIT**
Error persists on 1.1.3 as of (04/11/2022 at 16:06), log here: https://mclo.gs/HYQohH0
Error seems fixed on 1.1.4 as of (05/11/2022 at 18:50), will not close the issue waiting for confirmation from some dev

**Comment by NewJumper** [comment]
What platform did you run the mod on?

**Comment by otavio-silva** [comment]
@NewJumper I'm running on Windows 11, Temurin JDK 17, Minecraft 1.19.2 with Fabric 0.14.10.  You can find all info on the log link I posted on the **EDIT** section.

**Comment by ang-xd** [comment]
Fixed in 1.14.
