### ISSUE TITLE
Bug list - Version 'deeperdarker-forge-1.1.3-forge.jar'

### ISSUE THREAD

**Issue by Storm4ce** [KyaniteMods/DeeperAndDarker#99]
**Description**:
Sculk affinity potions do not have any effect
Mobs suffocate in sculk
Sculk snapper corrupts when tamed (results in server crashes upon rendering)
Warden is 500 HP (not nerfed) - this is to my preference (I would prefer a config to keep the Warden un-nerfed but I know it's a bug)

**To Reproduce**:

Use a sculk affinity potion

Have mobs spawn in deeper darker

Tame a sculk snapper

Summon a warden

**Comment by ang-xd** [comment]
Elaborate on "Mobs suffocate in sculk"

**Comment by ang-xd** [comment]
Unable to reproduce. Provide more information please

**Comment by Storm4ce** [comment]
> Elaborate on "Mobs suffocate in sculk"

snappers spawning inside the sculk and taking damage from suffocation. There's not really any more info I know how to provide other than the following - it's simply the problems I get - and apparently others on the Discord have had these problems too (warden un-nerfed, sculk snapper corruption)

**Comment by NewJumper** [comment]
Warden ***is*** nerfed. In vanilla it is supposed to have 500 HP and in Deeper Darker its supposed to have 350, which is exactly what is happening.
![image](https://user-images.githubusercontent.com/55116298/201568496-e6b92986-f3a8-4d23-afe7-3bc6be7de40c.png)

Providing a video of your issue, or any screenshots at least, would be helpful.

**Comment by Storm4ce** [comment]
![image](https://user-images.githubusercontent.com/117605286/201570090-b5b75de1-0a0a-4885-a562-0c67b2ccbad1.png)
500 hp. There was a period of time where it had 350hp until the update that added soul elytra and the new biome for us. I even uninstalled everything and reinstalled locally instead of the server - with no other mods to ensure it wasnt some conflict or anything, and just with a fresh minecraft and curseforge install, the same exact errors were present (snapper crash, suffocation, no warden nerf, sculk affinity being useless)

**Comment by ang-xd** [comment]
We were unable to replicate any of these issues. Tested on both Forge and Fabric.

**Comment by NewJumper** [comment]
Because we are unable to reproduce these issues, they must have been fixed or need further info from @Storm4ce.
Marked as stale, will be closed within a week if there is no response.
